### ISSUE TITLE
F# support

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [adamjimenez/shiftedit#100]
I see C# is supported, can we get F# support?

**Comment by adamjimenez** [comment]
I will add that to the next update.

On 27 January 2016 at 13:32, ImaginaryDevelopment <notifications@github.com>
wrote:

> I see C# is supported, can we get F# support?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adamjimenez/shiftedit/issues/100>.
>



-- 
Best regards,
Adam Jimenez
