### ISSUE TITLE
I can't save my files

### ISSUE THREAD

**Issue by Juanses** [adamjimenez/shiftedit#112]
It's pretty anoying http://puu.sh/mPDq5/971e0dd3ca.png
Specially since I've just payed for the Premium version

**Comment by adamjimenez** [comment]
Hi,

I need some context. Does this happen every time you save? Are you saving an existing file or a new file?

Does this happen on the Legacy release. Switch release channels from your account:
https://shiftedit.net/update-details

**Comment by Juanses** [comment]
Sorry, it's my server's fault
Sorry

**Comment by adamjimenez** [comment]
I'm glad it's working. Thank you for your support.
