### ISSUE TITLE
Tabs shrink too small when 10+ are open

### ISSUE THREAD

**Issue by andyiwest** [adamjimenez/shiftedit#113]
Tabs no longer have the scroll to see more effect, and so with a few tabs open, you can't read the page names anymore

![screen shot 2016-02-03 at 14 46 19](https://cloud.githubusercontent.com/assets/13347568/12785632/48d6ac52-ca85-11e5-911c-8c514c96ef64.png)

**Comment by adamjimenez** [comment]
Yes, it works more like Chrome now. If you hover over the tab it will display the file name.
The scrollers had some usability issues, particularly when trying to re-order tabs - it was a mess. I do not want to go back to that but you are not the first to comment on this. So if you have any ideas to improve this, let me know.

**Comment by andyiwest** [comment]
I'll have a think about alternatives
