### ISSUE TITLE
radio not clickable, just name

### ISSUE THREAD

**Issue by andyiwest** [adamjimenez/shiftedit#114]
the checkbox isn't part of the selectable area. Only clicking the text toggles it on/off

![screen shot 2016-02-03 at 14 50 38](https://cloud.githubusercontent.com/assets/13347568/12785701/a5039c06-ca85-11e5-9ef8-b000d9965ccc.png)

**Comment by andyiwest** [comment]
Working nicely, however, once you check a box, the menu minimizes, annoying if you want to select multiple boxes

**Comment by adamjimenez** [comment]
a lot of apps work that way, I'm tempted to leave as is.

**Comment by andyiwest** [comment]
maybe by holding an extra button while selecting an option could force the menu to stay open?
like a shift-click / ctrl-click etc..?
