### ISSUE TITLE
Cannot rename a file

### ISSUE THREAD

**Issue by eddieharrison** [adamjimenez/shiftedit#119]
When renaming a file, I get a popup;

Cannot rename file": chdir /public_html/

Version: 17.0.64

**Comment by eddieharrison** [comment]
This only seems to occur on a file name with & / &amp; in it
There is also an error with deleting the file too

**Comment by adamjimenez** [comment]
How can a file have "/" in it? Which server type?

**Comment by adamjimenez** [comment]
Oh wait the file has an ampersand in it?

**Comment by eddieharrison** [comment]
Yeah, you got it the second ampersand should have been &amp ;

**Comment by eddieharrison** [comment]
And FTP
