### ISSUE TITLE
Missing Autocomplete for HTML Attributes

### ISSUE THREAD

**Issue by ddouglas493** [adamjimenez/shiftedit#124]
When constructing a form, autocomplete does not detect the name attribute. Just thought i should report it. I am not sure if there are others but this is one that i have come across.

**Comment by adamjimenez** [comment]
what am I missing here:
![image](https://cloud.githubusercontent.com/assets/573192/13033943/582ee794-d31f-11e5-974d-06ff7e20eaee.png)

**Comment by ddouglas493** [comment]
Try on any input type text HTML field

**Comment by ddouglas493** [comment]
Here is a video of the issue

[ShiftEdit IDE HTML Autocomplete on HTML Forms Bug](https://www.youtube.com/watch?v=sMKcJfi0Xfo)

**Comment by adamjimenez** [comment]
Thanks I'm seeing it also.

On 14 February 2016 at 19:47, David Douglas <notifications@github.com>
wrote:

> Here is a video of the issue
>
> ShiftEdit IDE HTML Autocomplete on HTML Forms Bug
> <https://www.youtube.com/watch?v=sMKcJfi0Xfo>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adamjimenez/shiftedit/issues/124#issuecomment-183963721>
> .
>



-- 
Best regards,
Adam Jimenez

**Comment by adamjimenez** [comment]
This will be fixed in the next update.

**Comment by ddouglas493** [comment]
Thanks Man
