### ISSUE TITLE
Connection to host failed - on every site

### ISSUE THREAD

**Issue by anneallen** [adamjimenez/shiftedit#126]
Can't connect to any of my saved sites (which I have been using for months)  - Every one is "Connection to host failed"

**Comment by adamjimenez** [comment]
I am connecting ok, please check the troubleshooting guide:
https://shiftedit.net/docs/troubleshooting

**Comment by anneallen** [comment]
Thx - the ips were blacklisted by a couple of different hosting packages
I have removed the block and all good now
Thx
