### ISSUE TITLE
Folder tree does not always open correctly

### ISSUE THREAD

**Issue by sp-townsend** [adamjimenez/shiftedit#128]
When opening a website for editing, often the public_html folder very often cannot be opened.  After many reloads, it eventually enables the subtree to be opened.  This happens on all URLs I work on, and from different PC devices. I use the Chrome browser. The uploaded image shows no subfolders in the public_html folder, despite having a myriad of file and folders beneath it.
![screen shot 2016-02-19 at 10 03 06](https://cloud.githubusercontent.com/assets/17334198/13172664/2354c676-d6f1-11e5-9285-d1ac0a52e68a.png)

**Comment by adamjimenez** [comment]
FTP?

It's working ok for me.
If there are a lot of files and subfolders open it could be getting stuck when it tries to restore them all in one go. Can you see what comes back in chrome's network panel?

If your server supports PHP, you should find that turbo mode is faster:
https://shiftedit.net/docs/sites#turbo_mode

**Comment by digger149** [comment]
It's failing to load several folders for me too, I think it's folders I have been working in. 
Rather than keep refreshing the whole tree, I can open the particular folder by right-click -> reload on any folder

**Comment by sp-townsend** [comment]
Yes ... it is the folders I have been working in... which are the ones I want to access :(

**Comment by adamjimenez** [comment]
We try to list all the directories in one go for faster loading. I can disable this to fix the issue but it will also slow things down. I'm not seeing this issue on any of my sites so it's hard to know what's going on. If anybody can set me up a test ftp account please send the details to adam.jimenez@gmail.com

**Comment by hamza-sabaseo** [comment]
I am also experiencing this problem.
![screen shot 2016-02-19 at 12 31 27 pm](https://cloud.githubusercontent.com/assets/17344670/13188219/d0e65f1c-d704-11e5-987b-c10dcdd996f8.png)

**Comment by adamjimenez** [comment]
Thanks, I can reproduce an issue when there is no path set. I'm working on it. Usually I'd have the path set to public_html or equivalent.

**Comment by adamjimenez** [comment]
I've uploaded a fix for this issue, let me know how you get on.

**Comment by hamza-sabaseo** [comment]
Thank you, its working fine now.  All files and folders load the first time around.

**Comment by adamjimenez** [comment]
great, thanks for letting me know
