### ISSUE TITLE
Folders not deleting

### ISSUE THREAD

**Issue by hamza-sabaseo** [adamjimenez/shiftedit#131]
When an entire folder is selected, its contents are not deleted.  The only way to delete anything is to select the individual files.  We should be able to delete folders and have a confirmation afterwards.

**Comment by adamjimenez** [comment]
This is working for me over ftp with turbo mode on and off. I tried one folder in the root containing one file.

**Comment by hamza-sabaseo** [comment]
I am experiencing this problem with folders containing folders containing files.  For example, WordPress' "Uploads" folder.

**Comment by adamjimenez** [comment]
I've successfully tested deleting folders that contain subfolders and more
files.
The loading bar should list each file as it's deleted.
It needs to list all the files and folders before deleting them. The more
files you have, the longer this will take.

On 24 February 2016 at 18:23, hamza-sabaseo <notifications@github.com>
wrote:

> I am experiencing this problem with folders containing folders containing
> files.  For example, WordPress' "Uploads" folder.
>
> Sent from BlueMail
>
>
>
> On Feb 24, 2016, 10:10 AM, at 10:10 AM, Adam Jimenez <
> notifications@github.com> wrote:
> >This is working for me over ftp with turbo mode on and off. I tried one
> >folder in the root containing one file.
> >
> >---
> >Reply to this email directly or view it on GitHub:
> >
> https://github.com/adamjimenez/shiftedit/issues/131#issuecomment-188387001
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adamjimenez/shiftedit/issues/131#issuecomment-188391521>
> .
>



-- 
Best regards,
Adam Jimenez
