### ISSUE TITLE
I think its broke

### ISSUE THREAD

**Issue by McAdams12** [adamjimenez/shiftedit#132]
It wont let me upload my website from the local drive to the server. Please help!!

It says this"Error opening file: 230 OK. Current restricted directory is /"

**Comment by McAdams12** [comment]
It says this 
"Error opening file: 230 OK. Current restricted directory is /"

**Comment by adamjimenez** [comment]
I need some context, have you connected to an ftp server (or other). What steps are you using to  upload the files? A screenshot might also help.
