### ISSUE TITLE
cannot write anything, copy anything or save.

### ISSUE THREAD

**Issue by bnichifor** [adamjimenez/shiftedit#135]
Hi, I am working on a school project using shiftedit, and for the past couple of weeks I have been unable to progress with it, as shiftedit will not allow me to type anything on pages, or copy any code in pages. Also quite frequently, I have it so I cannot save pages, so I'll have to copy them to a word document and try a few hours later until it works.

any help would be appreciated. I already tried deleting all my cookies

**Comment by adamjimenez** [comment]
If you're not using chrome, please try it in chrome if possible.

On 26 February 2016 at 12:39, bnichifor <notifications@github.com> wrote:

> Hi, I am working on a school project using shiftedit, and for the past
> couple of weeks I have been unable to progress with it, as shiftedit will
> not allow me to type anything on pages, or copy any code in pages. Also
> quite frequently, I have it so I cannot save pages, so I'll have to copy
> them to a word document and try a few hours later until it works.
>
> any help would be appreciated. I already tried deleting all my cookies
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adamjimenez/shiftedit/issues/135>.
>



-- 
Best regards,
Adam Jimenez

**Comment by bnichifor** [comment]
I am using chrome, it seems that the problem is sometimes fixed when I click off shift edit on another tab, and back on. The problem also seems to be occurring when I navigate between files in different folders. I would have to copy the code from one file on a word document then re-copy it from the word document and then on the intended file, only if the 2 files are in different folders

**Comment by adamjimenez** [comment]
Perhaps this is an extension issue, try running from an incognito window
(ctrl-shift-n) to stop extensions from interfering.

On 26 February 2016 at 13:28, bnichifor <notifications@github.com> wrote:

> I am using chrome, it seems that the problem is sometimes fixed when I
> click off shift edit on another tab, and back on. The problem also seems to
> be occurring when I navigate between files in different folders. I would
> have to copy the code from one file on a word document then re-copy it from
> the word document and then on the intended file, only if the 2 files are in
> different folders
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adamjimenez/shiftedit/issues/135#issuecomment-189272725>
> .
>



-- 
Best regards,
Adam Jimenez

**Comment by bnichifor** [comment]
I'll get back to you on that one, as the school computers don't allow incognito mode, however there aren't any extensions apart from some google docs stuff, however I'll give it a try

**Comment by adamjimenez** [comment]
Are there any errors in the JS console? ctrl-shift-j.
Perhaps some of these lockdown restrictions are causing issues.

On 26 February 2016 at 13:50, bnichifor <notifications@github.com> wrote:

> I'll get back to you on that one, as the school computers don't allow
> incognito mode, however there aren't any extensions apart from some google
> docs stuff, however I'll give it a try
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adamjimenez/shiftedit/issues/135#issuecomment-189284829>
> .
>



-- 
Best regards,
Adam Jimenez
