### ISSUE TITLE
App is completely messed up at startup. Can't login

### ISSUE THREAD

**Issue by voxelmator** [adamjimenez/shiftedit#136]
It is impossible to login since Feb 22nd.
Most of the interface elements of front page are missing.

**Comment by adamjimenez** [comment]
works for me.
try clearing cache or post a screenshot.

**Comment by voxelmator** [comment]
Dear Adam,
I am trying the cache...
How many users are using ShiftEdit ? This workspace is so nice. I am
surprised you only have few followers.
Best regards,
Philippe

2016-02-27 0:25 GMT+01:00 Adam Jimenez <notifications@github.com>:

> works for me.
> try clearing cache or post a screenshot.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adamjimenez/shiftedit/issues/136#issuecomment-189524350>
> .
>



-- 
Philippe PUECH, MD, PhD
Chef de service en Imagerie Néphro-Urologique, ORL et Hématologique
Chairman of Genitourinary, ENT and Hematologic Imaging Department
Lille University Hospital
Inserm, U1189 research lab
puech@dicomworks.com
+33 3 20 44 61 91 (office)
+33 3 20 44 59 83 (direct)
http://www.dicomworks.com
http://www.onco-thai.fr
http://www.pcih.fr/alip
http://fr.linkedin.com/pub/philippe-puech/41/b42/856 (LinkedIn)

**Comment by voxelmator** [comment]
Dear Adam,

Unfortunately the cache solution did not work. Here is a screenshot of what
I get when i log on the main page with Chrome, IE and Firefox:

[image: Images intégrées 1]

2016-02-27 0:25 GMT+01:00 Adam Jimenez <notifications@github.com>:

> works for me.
> try clearing cache or post a screenshot.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adamjimenez/shiftedit/issues/136#issuecomment-189524350>
> .
>



-- 
Philippe PUECH, MD, PhD
Chef de service en Imagerie Néphro-Urologique, ORL et Hématologique
Chairman of Genitourinary, ENT and Hematologic Imaging Department
Lille University Hospital
Inserm, U1189 research lab
puech@dicomworks.com
+33 3 20 44 61 91 (office)
+33 3 20 44 59 83 (direct)
http://www.dicomworks.com
http://www.onco-thai.fr
http://www.pcih.fr/alip
http://fr.linkedin.com/pub/philippe-puech/41/b42/856 (LinkedIn)

**Comment by adamjimenez** [comment]
I can't see the screenshot.
Are you behind a restrictive firewall?

**Comment by voxelmator** [comment]
Probably. I am working in an hospital. Had a similar problem at home, but
it may be due to bad connection. I could log in yesterday from home, after
the cache cleanup. But it is still not working in the hospital since 2 to 5
days. Can not be sure. here is another. Thank you for your time.

2016-02-27 10:12 GMT+01:00 Adam Jimenez <notifications@github.com>:

> I can't see the screenshot.
> Are you behind a restrictive firewall?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adamjimenez/shiftedit/issues/136#issuecomment-189609720>
> .
>



-- 
Philippe PUECH, MD, PhD
Chef de service en Imagerie Néphro-Urologique, ORL et Hématologique
Chairman of Genitourinary, ENT and Hematologic Imaging Department
Lille University Hospital
Inserm, U1189 research lab
puech@dicomworks.com
+33 3 20 44 61 91 (office)
+33 3 20 44 59 83 (direct)
http://www.dicomworks.com
http://www.onco-thai.fr
http://www.pcih.fr/alip
http://fr.linkedin.com/pub/philippe-puech/41/b42/856 (LinkedIn)

**Comment by adamjimenez** [comment]
They might be blocking the resources from S3. You can probably see what's being blocked on chrome's network panel.
Again no screenshot.
