### ISSUE TITLE
duplicating php files turn into folders instead of file

### ISSUE THREAD

**Issue by pdgehrke** [adamjimenez/shiftedit#138]
Issue that just started happening to me in the last 2-3 days. With the site folder directory open, using right click to duplicate on an existing php file (example.php) has an end result of the example (1) .php as a folder instead of a file. Looks like the (1) is disrupting the file extension.

**Comment by adamjimenez** [comment]
This is working for me in the latest dev release. Can you try it? switch release channel from:
https://shiftedit.net/update-details

**Comment by pdgehrke** [comment]
That did the trick! I Love the program and the new ui as well. Thanks for getting back to me so quick. Have a good one!

**Comment by adamjimenez** [comment]
Thank you. I will push to stable soon.
