### ISSUE TITLE
Master Password

### ISSUE THREAD

**Issue by richbishop** [adamjimenez/shiftedit#139]
After initially inputting Master Password when logging in, at random intervals it will say there is no Master Password, and I have to hard-reload the browser window.

Further to this, when I have tried to turn off the Master Password to see if that solves the issue, I am told my Master Password is incorrect, which is a false negative.

This appears intermittently every week or so, but once it appears, it will keep erroring over several hours.

**Comment by adamjimenez** [comment]
I think the session is expiring. I've got a fix for not being able to remove the master password.

**Comment by richbishop** [comment]
Still isn't working :( Is the fix live yet? Thx

**Comment by adamjimenez** [comment]
It's on dev channel
