### ISSUE TITLE
Lines of code disappear

### ISSUE THREAD

**Issue by Johnttt** [adamjimenez/shiftedit#140]
For instance, Shiftedit erases the java code for facebook buttons on an html page some time after I save it. This is not the only time this has happened, just the latest. I'll edit a page, publish it the changes show up and suddenly the new code is no longer there.

**Comment by adamjimenez** [comment]
I haven't seen this and can't understand how it could be happening.
Which type of server is it? e.g. ftp
Do you have steps to reproduce this issue?

On 16 March 2016 at 22:43, Johnttt <notifications@github.com> wrote:

> For instance, Shiftedit erases the java code for facebook buttons on an
> html page some time after I save it. This is not the only time this has
> happened, just the latest. I'll edit a page, publish it the changes show up
> and suddenly the new code is no longer there.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/adamjimenez/shiftedit/issues/140>
>



-- 
Best regards,
Adam Jimenez

**Comment by Johnttt** [comment]
I'm using ftp. I'm not understanding exactly when it happens yet. If I can
reliably reproduce I'll post back. I'm not using shifedit a lot but it has
still happened to me a couple of times over the last month. I just
discovered I can go back into revision history and find the missing code.
That helps.

I like the program. Thank you for responding!

John Tittle
Tittle Real Estate
651-764-4604
1-800-587-4950
Homes for sale in Red Wing
<http://tittlerealestate.com/zip/55066?source=gmail>
featured listings <http://tittlerealestate.com/featured?+source=gmail>
