### ISSUE TITLE
Error opening file: chdir

### ISSUE THREAD

**Issue by daddymack** [adamjimenez/shiftedit#141]
Love Shiftedit.  Using it for about 15 sites and it works great.  I just added a new site to it and after opening fine, I can open and edit each file (.html, .css, .js) but I cannot open any of the folders.  When I try to open, I get error: Error opening file: chdir

Each folder instead of a folder icon has just a white page icon.

**Comment by adamjimenez** [comment]
Thanks! Which server type e.g. FTP?
Might need to enter a path in the site settings.

**Comment by daddymack** [comment]
FTPS - FTP over implicit TLS/SSL
site settings in shiftedit
host: ftps://XZM737-SITE0001.MaxEsp.net
username: XZM737-SITE0001.MaxEsp.net\caseymack@xzm737
pw: Cem72406!
path: \smithmusic\

Opens files in that smithmusic folder but I cannot go to any directory
inside smithmusic folder and I get the original error

**Comment by adamjimenez** [comment]
Thanks - I deleted your msg within a minute of seeing it as these messages are publicly visible. I suggest you change your password for good measure. If you need to send me anything private - email to adam@shiftcreate.com

I've pushed a fix for this issue.
