### ISSUE TITLE
File view missing

### ISSUE THREAD

**Issue by jlliska** [adamjimenez/shiftedit#142]
In the past, I've been able to see all of the files I have in the first column.  I logged in today to update a few things on a website and I can't see anything there.  How can I get this list back?

![screenshot 2016-03-25 at 19 38 53](https://cloud.githubusercontent.com/assets/18079358/14057332/1a85501e-f2c2-11e5-8bb0-0ca889583e96.png)

**Comment by adamjimenez** [comment]
Not sure what has happened here, try refreshing the browser. If it happens
again check the js console for errors.

On 26 March 2016 at 01:49, jlliska <notifications@github.com> wrote:

> In the past, I've been able to see all of the files I have in the first
> column. I logged in today to update a few things on a website and I can't
> see anything there. How can I get this list back?
>
> [image: screenshot 2016-03-25 at 19 38 53]
> <https://cloud.githubusercontent.com/assets/18079358/14057332/1a85501e-f2c2-11e5-8bb0-0ca889583e96.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/adamjimenez/shiftedit/issues/142>
>



-- 
Best regards,
Adam Jimenez

**Comment by jlliska** [comment]
Thanks for replying!  I've tried refreshing the browser, and signing out
and logging in again, but nothing's changed.  On a new tab, I can open
recently edited files and save them, but I just can't see my file tree.
How would I check the js console for errors?

**Comment by adamjimenez** [comment]
Ctrl-shift-j in chrome

On 31 March 2016 at 18:11, jlliska <notifications@github.com> wrote:

> Thanks for replying! I've tried refreshing the browser, and signing out
> and logging in again, but nothing's changed. On a new tab, I can open
> recently edited files and save them, but I just can't see my file tree.
> How would I check the js console for errors?
>
> On 28 March 2016 at 04:06, Adam Jimenez <notifications@github.com> wrote:
>
> > Not sure what has happened here, try refreshing the browser. If it
> happens
> > again check the js console for errors.
> >
> > On 26 March 2016 at 01:49, jlliska <notifications@github.com> wrote:
> >
> > > In the past, I've been able to see all of the files I have in the first
> > > column. I logged in today to update a few things on a website and I
> can't
> > > see anything there. How can I get this list back?
> > >
> > > [image: screenshot 2016-03-25 at 19 38 53]
> > > <
> >
> https://cloud.githubusercontent.com/assets/18079358/14057332/1a85501e-f2c2-11e5-8bb0-0ca889583e96.png
> > >
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/adamjimenez/shiftedit/issues/142>
> > >
> >
> >
> >
> > --
> > Best regards,
> > Adam Jimenez
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/adamjimenez/shiftedit/issues/142#issuecomment-202331404
> >
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/adamjimenez/shiftedit/issues/142#issuecomment-204027035>
>



-- 
Best regards,
Adam Jimenez

**Comment by jlliska** [comment]
And once I find an error, what should I do about that?

[image: Inline images 1]

**Comment by adamjimenez** [comment]
I can't see the image. Please report the error here.

**Comment by jlliska** [comment]
The error says "Mixed content: The
https://shiftedit.s3.amazonaws.com/shiftedit-17.0.75.js:8706 page at '
https://shiftedit.net/home' was loaded over HTTPS, but requested an
insecure XMLHttpRequest endpoint '
http://shiftedit.s3.amazonws.com/js/insecure.js'. This request has been
blocked; the content must now be served over HTTPS."

I also have a warning: "Update your TinyMCE CDN url to: //
cdn.tinymce.com/4/tinymce.min.js"

**Comment by adamjimenez** [comment]
Those are expected warnings.

**Comment by jlliska** [comment]
So, do you have any other suggestions in regards to how I can see my list
of files?  I still just have a file icon in the left-side column with
nothing else.

**Comment by adamjimenez** [comment]
Does it work from an incognito window? (ctrl-shift-n)

**Comment by jlliska** [comment]
No, it doesn't.

**Comment by adamjimenez** [comment]
Not sure what is going on here. Have you tried on a different machine?
Does it only happen on this one site?
Have you tried removing the site and adding it again?

If it's still happening and only for this one site then please send the server connection details to adam@shiftcreate.com and I will investigate.
