### ISSUE TITLE
Connecting to FTP server

### ISSUE THREAD

**Issue by Juanses** [adamjimenez/shiftedit#143]
It works with FileZilla but not with ShiftEdit.
It used to work but suddenly it doesn't anymore

**Comment by adamjimenez** [comment]
what error do u get?
you might need to allow our ips:
https://shiftedit.net/docs/troubleshooting

If you'd like me to investigate pls email the server details to
adam@shiftcreate.com

On 27 March 2016 at 15:04, Juanses <notifications@github.com> wrote:

> It works with FileZilla but not with ShiftEdit.
> It used to work but suddenly it doesn't anymore
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/adamjimenez/shiftedit/issues/143>
>



-- 
Best regards,
Adam Jimenez

**Comment by brothersun** [comment]
In the ShiftEdit folder pane, the files on my FTP server are listed however all the dates are listed as  12/31/1969.

**Comment by brothersun** [comment]
I've used ShiftEdit years ago on my Chromebook with no problems, but now I'm trying it on my Win 8.1 laptop. In addition to the file dates not being picked up, I just realized that Ctrl-V does not work for Paste. I'm sure I must have used Paste before, so this is probably a Win 8.1 or Firefox problem. Any ideas?

**Comment by adamjimenez** [comment]
You can use the context menu options, the keyboard shortcuts will be fixed in the next update.

**Comment by brothersun** [comment]
Actually, paste is working fine now. It was only disabled during one
session that I encountered the problem, so I think it was due to some
hardware quirk on my side. Thanks.
