### ISSUE TITLE
Revision History not working

### ISSUE THREAD

**Issue by KireniaV** [adamjimenez/shiftedit#152]
Hm... It looks like there was an earlier closed thread on this, but I can't seem to get the revision history to work. I'm on stable. I've just been working on the file with my collaborators and we each saved it at various times but it shows only one date/time of revision with a strange date (tomorrow!) and doesn't show any other previous versions:
![image](https://cloud.githubusercontent.com/assets/5215200/14446978/32f6e074-0021-11e6-8565-637b7f840d98.png)

**Comment by adamjimenez** [comment]
Hi, are you and your collaborators all using Premier version?

**Comment by KireniaV** [comment]
Nope, just me! I've shared the site with my programming club, a group of three of us that meet online to work on projects in our spare time. Usually in the past I could view the revision history and restore a previous revision if needed.

Thanks!
--Kaitlyn

Sent from my Windows Phone
________________________________

**Comment by adamjimenez** [comment]
I can't see why this wouldn't work, as long as you are saving the files under your premier account and the file size is <1MB

**Comment by adamjimenez** [comment]
Edit Site -> Advanced. Make sure revisions per file > 0
