### ISSUE TITLE
Error saving

### ISSUE THREAD

**Issue by slavikator** [adamjimenez/shiftedit#153]
Using chrome cant save anithing!!!

Error saving file: Failed saving concerts.php: delete concerts.php

shiftedit-17.0.75.js:8706 Mixed Content: The page at 'https://shiftedit.net/home' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://shiftedit.s3.amazonaws.com/js/insecure.js'. This request has been blocked; the content must be served over HTTPS.

Uncaught TypeError: Cannot read property 'getTokens' of null

Application Cache Error event: Resource fetch failed (2) https://shiftedit.s3.amazonaws.com/shiftedit-17.0.75.js

**Comment by adamjimenez** [comment]
possible file permissions issue. If you'd like me to investigate please email me details direct adam@shiftcreate.com
