### ISSUE TITLE
I have a problem with view of directory on the left ...

### ISSUE THREAD

**Issue by cjnatali** [adamjimenez/shiftedit#155]
Hello,

I have a problem when viewing the file tree (left view). When I have two directories "PICOLight" and "PICOLight - child", "PICOLight - child" shows the tree "PICOLight" and a click on one of the files shows "Error opening file: chdir /" (See screenshots attached). The bug has existed for several months I expected it to be corrected but today it is still not and it starts to ask me problem.

Cordially.
![capture1](https://cloud.githubusercontent.com/assets/17564238/14943077/08239b80-0fd0-11e6-9375-7b72efb051e2.JPG)
![capture2](https://cloud.githubusercontent.com/assets/17564238/14943078/082437f2-0fd0-11e6-875c-c55e1403add2.JPG)

**Comment by adamjimenez** [comment]
I've pushed a change that may fix this.
If you still have trouble please email ftp connection details to adam@shiftcreate.com and I will investigate.

**Comment by cjnatali** [comment]
Thanks. It's ok.
