### ISSUE TITLE
Connection Timed Out Error 

### ISSUE THREAD

**Issue by Jeandsmith** [adamjimenez/shiftedit#162]
As soon as I open the application, the application pops a message saying **Connection To Host Failed**

**Comment by adamjimenez** [comment]
https://shiftedit.net/docs/troubleshooting

On 24 May 2016 at 08:18, JaMES <notifications@github.com> wrote:

> As soon as I open the application, the application pops a message saying *Connection
> To Host Failed*
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/adamjimenez/shiftedit/issues/162>
>



-- 
Best regards,
Adam Jimenez
