### ISSUE TITLE
Revision history not working

### ISSUE THREAD

**Issue by sepa85** [adamjimenez/shiftedit#163]
Hi, the revision system does not work. The window appears always empty and there are any revert possibility. Sometimes the system change with no warning the opened file content (with loss on data modified). If i press CTRL+Z on the auto changed files, they appear empty.

**Comment by adamjimenez** [comment]
If you are collaborating the shared file may be different from the saved file.
You can get the saved file back by doing File -> Revert to saved.

Revision history is available to premier users only. Make sure the revisions per file is greater than 0 in site settings -> advanced.
