### ISSUE TITLE
FTP acces

### ISSUE THREAD

**Issue by slavikator** [adamjimenez/shiftedit#172]
Hi!
I have IP filter for ftp accesing. What ip need to place in this filter for warking shiftedit correctly? Now i can see files but cant wright them.

**Comment by adamjimenez** [comment]
from: https://shiftedit.net/docs/troubleshooting
54.235.66.128
54.204.38.137
54.197.226.18

If you can see the files, you should be able to write to them. Check the file permissions.

**Comment by slavikator** [comment]
I have file .ftpaccess with filter. If I AllowAll - Shiftedit can wright.
In my actual setting can reed, but cant wright.

<Limit Write>
Allow 91.243.0.0/19 #23.04.2016 11:18:25
Allow 91.243.26.38 #23.04.2016 11:18:25
Allow 80.91.191.0/26 #28.10.2015 19:30:22
Allow 80.91.191.38 #28.10.2015 19:30:22
Allow 213.109.224.0/20 #22.12.2015 16:17:27
Allow 213.109.238.195 #22.12.2015 16:17:27
Allow 213.109.224.0/20 #22.12.2015 16:17:27
Allow 213.109.238.195 #22.12.2015 16:17:27
Allow 80.93.124.0/24 #17.06.2016 11:25:02
Allow 80.93.124.58 #19.04.2016 06:21:31
Allow 93.175.192.0/20 #17.06.2016 10:59:57
Allow 93.175.192.226 #12.05.2016 13:59:15
Allow 93.175.192.227 #17.06.2016 10:59:57
Allow 80.93.124.59 #17.06.2016 11:25:02
DenyAll
</Limit>

Не йди попереду мене, бо я можу не піти за тобою.
Не йди позаду мене, бо я можу не повести тебе.
А йди поруч, і будь моїм другом!

www.amplituda.if.ua

2016-06-17 11:50 GMT+03:00 Adam Jimenez <notifications@github.com>:

**Comment by adamjimenez** [comment]
our ips aren't in there?

**Comment by slavikator** [comment]
dont know tour ips

Не йди попереду мене, бо я можу не піти за тобою.
Не йди позаду мене, бо я можу не повести тебе.
А йди поруч, і будь моїм другом!

www.amplituda.if.ua

2016-06-17 15:02 GMT+03:00 Adam Jimenez <notifications@github.com>:

**Comment by adamjimenez** [comment]
see my [earlier comment](https://github.com/adamjimenez/shiftedit/issues/172#issuecomment-226715663)

**Comment by slavikator** [comment]
​​
ok. Thanks.
