### ISSUE TITLE
Collaboration error

### ISSUE THREAD

**Issue by giomarco** [adamjimenez/shiftedit#174]
Hi,
i have a Supporter profile on shitedit. I'm collaborating in a project created by a Premier user. 
If he share the entire project with me, when we both try to open a file it result empty. If he delete the collaboration with me, all works great (only for him). 
It happened form yesterday when my free trial is expired. I've already try to loggin out and in several times, change browser and use anonymous tab on chrome.

What's the issue?

**Comment by adamjimenez** [comment]
Are there any errors in the js console? ctrl-shift-j

On 29 June 2016 at 23:25, giomarco <notifications@github.com> wrote:

> Hi,
> i have a Supporter profile on shitedit. I'm collaborating in a project
> created by a Premier user.
> If he share the entire project with me, when we both try to open a file it
> result empty. If he delete the collaboration with me, all works great (only
> for him).
> It happened form yesterday when my free trial is expired. I've already try
> to loggin out and in several times, change browser and use anonymous tab on
> chrome.
>
> What's the issue?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/adamjimenez/shiftedit/issues/174>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAi_CGzWSpndjMb2RXgCNTBzx9eWGSg6ks5qQvDogaJpZM4JBoOE>
> .
>



-- 
Best regards,
Adam Jimenez
