### ISSUE TITLE
Godaddy Managed Hosting - unable to save CSS or Txt file edits

### ISSUE THREAD

**Issue by anneallen** [adamjimenez/shiftedit#176]
But, can save php?

Hangs,  then if press cancel get "error saving file" and then the next time you open the file, completely empty (which is a disaster if it is a 3000 line CSS file with unique CSS code)

This is the 2nd time I have come across this issue with Godaddy Managed Wordpress hosting

**Comment by adamjimenez** [comment]
Can you get the file back in revision history?

On 13 July 2016 at 22:21, Anne Allen <notifications@github.com> wrote:

> But, can save php?
>
> Hangs, then if press cancel get "error saving file" and then the next time
> you open the file, completely empty (which is a disaster if it is a 3000
> line CSS file with unique CSS code)
>
> This is the 2nd time I have come across this issue with Godaddy Managed
> Wordpress hosting
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/adamjimenez/shiftedit/issues/176>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAi_CIJo-d-r1LwrfmrKZ0hPMyhKwmW0ks5qVVbmgaJpZM4JL3Jt>
> .
>



-- 
Best regards,
Adam Jimenez

**Comment by anneallen** [comment]
No

As this is the 2nd time it has happend (last time was on a mega urgent site
move) I just created the wordpress site and tested shiftedit on a standard
theme - so no loss this time, but on both occasions this is a new ftp site
so no revision history

**Comment by adamjimenez** [comment]
This is difficult to diagnose without being able to recreate the issue.
If there is an error saving, try to save again and if in doubt copy the
contents to an empty file.

On 13 July 2016 at 22:26, Anne Allen <notifications@github.com> wrote:

> No
>
> As this is the 2nd time it has happend (last time was on a mega urgent site
> move) I just created the wordpress site and tested shiftedit on a standard
> theme - so no loss this time, but on both occasions this is a new ftp site
> so no revision history
>
>
>
> On Wed, Jul 13, 2016 at 2:24 PM, Adam Jimenez <notifications@github.com>
> wrote:
>
> > Can you get the file back in revision history?
> >
> > On 13 July 2016 at 22:21, Anne Allen <notifications@github.com> wrote:
> >
> > > But, can save php?
> > >
> > > Hangs, then if press cancel get "error saving file" and then the next
> > time
> > > you open the file, completely empty (which is a disaster if it is a
> 3000
> > > line CSS file with unique CSS code)
> > >
> > > This is the 2nd time I have come across this issue with Godaddy Managed
> > > Wordpress hosting
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/adamjimenez/shiftedit/issues/176>, or mute the
> > thread
> > > <
> >
> https://github.com/notifications/unsubscribe/AAi_CIJo-d-r1LwrfmrKZ0hPMyhKwmW0ks5qVVbmgaJpZM4JL3Jt
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Best regards,
> > Adam Jimenez
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/adamjimenez/shiftedit/issues/176#issuecomment-232491268
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AEX1Hf8bzwhyu9zoNzhNthPpotGx9Lt5ks5qVVeGgaJpZM4JL3Jt
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/adamjimenez/shiftedit/issues/176#issuecomment-232491762>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAi_COiG_Tx3l2PndMH_UVHqFZH6Ytm9ks5qVVf7gaJpZM4JL3Jt>
> .
>



-- 
Best regards,
Adam Jimenez
