### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by stefyonweb** [adamjimenez/shiftedit#177]
Hi,
I'm trying to add a new website, ad I always did.
I get this error: Error getting files: 230 OK. Current directory is / 
I can correcty connect with Filezilla

Thank you in advance
Stefania

**Comment by adamjimenez** [comment]
The message says it's connecting.
Could be the path needs to be updated - see what the remote path is in filezilla and then edit the site settings.
If you'd like me to investigate please email connection details to adam@shiftcreate.com
