### ISSUE TITLE
Cannot create/rename file in s3

### ISSUE THREAD

**Issue by Sciencegeek123** [adamjimenez/shiftedit#181]
I'm trying to create a file named "home.html" in a folder within s3. The folder is root level, and I was able to do this earlier today successfully with a different file.

The full path of the file I'm trying to create would be: "/web/home.html"

Upon creating the file and renaming it, I'm presented with an error stating:
Cannot rename file":

Not a particularly helpful error I'm afraid.

**Comment by Sciencegeek123** [comment]
Also, I can upload a file named "home.html" to the directory through the s3 console.

**Comment by Sciencegeek123** [comment]
Oddly enough I can also rename the file I uploaded.

**Comment by geoffreykolbe** [comment]
I can create a file, but I cannot make changes and save a file. I could do everything fine yesterday....

**Comment by adamjimenez** [comment]
I can create and edit files ok. It could have been an aws issue or to do with a specific region. Somewhat related I've pushed a fix for an issue with renaming/ deleting folders in S3.
