### ISSUE TITLE
How do you upload an image file from Google Drive to an ftp website?

### ISSUE THREAD

**Issue by geoffreykolbe** [adamjimenez/shiftedit#182]
If I try to upload an image file to an ftp site, Shiftedit tries to show the file as a text file in the editor. Basically, this means I can only move text files about which is only a little bit useful.

**Comment by adamjimenez** [comment]
Hi,

If you are using premier or supporter edition then you can have both sites added to shiftedit. Then open the GDrive site, right click the file in the tree and go to Edit -> Copy. Then open the ftp site. Right click the destination folder and go to Edit -> Paste
