### ISSUE TITLE
Issues!!!!

### ISSUE THREAD

**Issue by csf30816** [adamjimenez/shiftedit#184]
I am trying to make an HTML file and when I click new it does not let me click HTML

**Comment by coke11** [comment]
Are you running Cpanel?

**Comment by adamjimenez** [comment]
Are you using chrome?

**Comment by csf30816** [comment]
Yes, I am running chrome

**Comment by csf30816** [comment]
@coke11 I was trying to link FTP to it.

**Comment by csf30816** [comment]
Also it is taking for ever to save!

**Comment by adamjimenez** [comment]
Are there any console errors (ctrl shift j)?
I'm assuming this is from the file tree context menu. A screenshot might be
useful.

**Comment by csf30816** [comment]
I'll check the console, sorry no screen shots

**Comment by adamjimenez** [comment]
Are you using ftp? If so and your server supports php then consider
enabling turbo mode in site settings.

**Comment by csf30816** [comment]
Uploaded SS and I am was having troubles with FTP but now not really

**Comment by csf30816** [comment]
![capture](https://cloud.githubusercontent.com/assets/18520232/17459266/1aa0586c-5bf6-11e6-823c-09b2bc1c5520.JPG)

**Comment by adamjimenez** [comment]
No file listing. Did you add a site and connect to ftp?

**Comment by csf30816** [comment]
I did earlier but it still did not let me so I deleted it, sorry
