### ISSUE TITLE
Folder does not open

### ISSUE THREAD

**Issue by ctdh** [adamjimenez/shiftedit#188]
Folder fails to open:
![shiftedit_and_inbox__19](https://cloud.githubusercontent.com/assets/22244030/18596408/e3da8ea4-7c40-11e6-8abc-23d3b87625de.jpg)
The Browser Console from https://shiftedit.net/home#newfile shows the following error:
`XMLHttpRequest cannot load http://www_mydomain_com/shiftedit-proxy.php?ModPagespeed=off&cmd=get&path=. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://shiftedit.net' is therefore not allowed access. The response had HTTP status code 404.
`
Shiftedit does not save files to the server either.
SSH seems to work ok

**Comment by adamjimenez** [comment]
Try unticking turbo mode in site settings.
