### ISSUE TITLE
SSH terminal cursor will not stay on screen - Firefox only

### ISSUE THREAD

**Issue by Dbonejones** [adamjimenez/shiftedit#189]
In Firefox, if you start an SSH terminal and run enough commands to fill the screen, the window will not scroll to keep the cursor visible, makes the terminal panel unusable. Tested on 3 different computers running Firefox. Issue is not present in Chrome.

**Comment by adamjimenez** [comment]
Thanks for the report.
In Firefox the row height is 1 pixel bigger which threw out the calculation. I've pushed a fix to dev channel.
