### ISSUE TITLE
Eternal "subscription expired" popup after cancelling Premier

### ISSUE THREAD

**Issue by dougalx** [adamjimenez/shiftedit#192]
The modal titled "Your Subscription has Expired" will appear every time the user logs in, if the user had previously been paying for a Premier account but cancels and uses it for free.

Thanks Adam.

**Comment by adamjimenez** [comment]
it's kind of like WinRar

**Comment by dougalx** [comment]
So, this is an intentional nag? If so, I can understand.

**Comment by adamjimenez** [comment]
The supporter sub is available for $1 a month. or $10 a year.
