### ISSUE TITLE
Suggestion: Improve Find panel interactions.

### ISSUE THREAD

**Issue by mpmw** [adamjimenez/shiftedit#198]
The Find panel is inconvenient for keyboard-intensive users. It's not uncommon for programmers, especially those with lengthy files, to deactivate word-wrap. And it's obviously also not uncommon for those with lengthy files to heavily use the Find function. 

Currently, when a user presses Ctrl-F, the input focus is moved to the Search field. Depending on where the programmer is in his or her code, their code window horizontally scrolls when the Find panel opens. After finding the desired sting, there's no keyboard method back to the code window. Neither Escape nor Ctrl-K (a very likely next step) are available. One could use the Ctrl-Left key equivalent, but I stay away from it because it operates differently in various circumstances (e.g., it moves the cursor position in the code window). It's not intuitive to have to constantly think about the context in order to rapidly use a keyboard shortcut. Even if someone uses the keyboard shortcut to close the panel, their focus isn't returned to the code window.

So every time I search, I have to use the mouse to click back inside the document, close the Find panel, and return the horizontal scroll to the far left.

Suggestions:

1)  Offer alternate positions for the Find panel (e.g., horizontal or as separate window).

2)  Offer an optional compact version of the Find function as a single-line horizontal panel (with nothing but a Search and possibly Replace field).

3)  Have Ctrl-K return to document.

4)  Use ESC or some other shortcut to close the panel and return focus to the code window.

**Comment by adamjimenez** [comment]
quick tip: ctrl+\ will take you collapse the find panel and take you back into the editor.

**Comment by mpmw** [comment]
That's great to know. Thank you.

It's not listed in the Shortcut list.



<http://LucidQuotes.com>
