### ISSUE TITLE
Suggestion:  Customizable New tab...

### ISSUE THREAD

**Issue by mpmw** [adamjimenez/shiftedit#199]
...or the ability to deactivate it being shown.

Typically, programmers are working with the same small set of file types for any given project. For instance, a website might have html, js, php, and css files. Nothing else. All of the options aren't necessary.

**Comment by adamjimenez** [comment]
It's a good point.  I'm thinking the list could re-order itself depending on previous files that were created.  We could then show the most used file types with a more link to reveal the rest.

**Comment by mpmw** [comment]
Sounds good.



<http://LucidQuotes.com>

**Comment by adamjimenez** [comment]
I've pushed an update that enables you to drag and reorder the file types in a new tab.
The preferred file types are also then used in the file tree context menu when creating a new file.
The solution wasn't immediately obvious but I'm quite pleased how it turned out. Please let me know what you think of it.

**Comment by mpmw** [comment]
Wow, that is fantastic. Great design.

Perhaps it makes sense to consider increasing the line spacing so that it
can be faster for a mouse user to hit their target.

And for keyboard users, since there's no other place for the keyboard input
to go, I could see one or both of the following: Having the first nine or
ten Create items numbered, so that a user could quickly press Alt-N, then #
to quickly create the tab type of their choice. Or, since there's already
an input focus, and Enter already works, maybe even offering vertical and
horizontal cursor arrow navigation.

As for exposing the reordering functionality, if the highlighted item was
reversed (as in looking more like a selectable object with reasonable
padding versus just plain text), that might give someone a clue that, as an
object, it could be moved. Or maybe having fixed number column helps, since
someone locating the pointer over that column could show a move pointer.
The functionality would remain the same (i.e., click activates and drag
moves), but seeing the move cursor would advertise reordering.

All of the suggestions aside, it's already great.






<http://LucidQuotes.com>

**Comment by adamjimenez** [comment]
tweaked the line spacing and added a visual cue to indicate dragging.
the items can be navigated with tab, so I will leave that for now.

**Comment by mpmw** [comment]
Looks really good. The visual indication is great.



<http://LucidQuotes.com>

**Comment by adamjimenez** [comment]
Thanks, it's coming along.
