### ISSUE TITLE
Suggestion:  Consider more obvious indicator for current tab.

### ISSUE THREAD

**Issue by mpmw** [adamjimenez/shiftedit#202]
As it stands, orange is the default color throughout the product. In my opinion that makes the marking of an active tab in orange too subtle, if not misleading.

The reason I say "misleading" is that the active tab is orange, but the controls for it (on the next line) are blue. That means the color coding is saying that the controls apply to the inactive tab.

**Comment by mpmw** [comment]
I'd like to withdraw this suggestion. I should have considered the option to simply change schemes.

**Comment by adamjimenez** [comment]
No worries. Thanks for taking the time to put forward well thought out suggestions for improvements. We have a lot of users but relatively few provide such valuable feedback.
