### ISSUE TITLE
Suggestion: Saving new connections should not connect...

### ISSUE THREAD

**Issue by mpmw** [adamjimenez/shiftedit#204]
...or the button should be labeled accordingly.

**Comment by adamjimenez** [comment]
I've checked this and I can save an incorrect password without it trying to connect. It does try to connect if I tick turbo mode, but then it needs to, to upload the proxy file.
Please explain the issue in more detail.

**Comment by mpmw** [comment]
(As always, thank you for the follow-up.)

If I have an SFTP site open without Turbo mode, and I change the name of
the connection, it will reconnect.

Obviously, this isn't much of a problem, but I figured the behavior wasn't
intended.




<http://LucidQuotes.com>

**Comment by adamjimenez** [comment]
It will try to connect after it has saved. This is expected behaviour.
What would be incorrect is if it wouldn't save because it can't connect but that doesn't appear to be happening to me.

**Comment by mpmw** [comment]
I would expect it to connect if any of the communication settings were
altered, but not if it was just the ShiftEdit label.

Again, it's not a serious issue, but the reason I'm sensitive to it is that
some of the hosts that I use are extremely security conscious. If I mess up
the initial connection settings a couple of times, they blacklist my IP
until I contact their support department. Often times, it takes me a few
rounds of different settings to get it right, and I sometimes create
multiple connection profiles in the process. But, I imagine this is a
unique situation.



<http://LucidQuotes.com>

**Comment by adamjimenez** [comment]
ok, I see your point but I don't think the extra complexity is worth it unless others also want this feature.

**Comment by mpmw** [comment]
Yep. That makes sense.



<http://LucidQuotes.com>
