### ISSUE TITLE
Suggestion:  Option to download single file uncompressed.

### ISSUE THREAD

**Issue by mpmw** [adamjimenez/shiftedit#205]
Zipping definitely makes sense for multiple files, but is inconvenient when downloading single files.

Clarification: I mean from right-click menu in file list.

**Comment by adamjimenez** [comment]
Open the file and then File -> Download.

**Comment by mpmw** [comment]
Yep. That's why I added the clarification. It would be nice (but clearly
not essential) to have it in the file manager, as well.





<http://LucidQuotes.com>

**Comment by adamjimenez** [comment]
There was right click -> open -> download.
I will move this option to the main menu and fix a bug affecting latest chrome.
