### ISSUE TITLE
Suggestion: Set editing scope.

### ISSUE THREAD

**Issue by mpmw** [adamjimenez/shiftedit#210]
I imagine this one would be quite difficult to implement, but I'll throw it out there.

Many times, I want my editing to be confined to a single function. This is especially true in cases in which I have duplicated and renamed an existing function with the intent of applying it to another operation, or cases in which I might be changing the naming convention within a single function. Before adding the custom behavior, one usually customizes various aspects (e.g., element names). Search and Replace would be ideal to use, but it affects the entire file. So... 

It would be cool if a ShiftEdit user could set a function as having the editing scope, similar to how graphic editors allow users to select regions in which all changes are confined. It would even be nice for less destructive operations (e.g., using search within a scope to determine the number of occurrences of a given string).

**Comment by adamjimenez** [comment]
You can do find and replace in a selection by clicking the selection icon under the search box. Hope that helps.

**Comment by mpmw** [comment]
That definitely helps. Thank you.



<http://LucidQuotes.com>
