### ISSUE TITLE
Minified file parsing error.

### ISSUE THREAD

**Issue by mpmw** [adamjimenez/shiftedit#212]
When using the automatic minify feature with a very lengthy .js file, I often receive a parsing error ("unexpected token") on the very last line. If I delete the .min file from the directory, save again, and refresh the webpage, the parsing error goes away.

**Comment by adamjimenez** [comment]
That's weird that it's inconsistent. Does it look like the minified file is being truncated or what?
How big is the file?

**Comment by mpmw** [comment]
Given the steps described below, I don't think it's a truncation problem.

The un-minified file has 12,500+ lines. Its unreduced size is 369KB, and it
reduces to 305KB.

In order to generate the error (since I'm not currently coding in that
file), I took the following steps:

   1. I added eleven functions named test[#] (with the only action being
   writing to the console) *before* the last real function in the file.

   2. I saved the file with minify set to automatic, refreshed the website,
   and there was no problem.

   3. I then removed all of the test functions and re-saved the file (again
   with minify set to automatic).

   4. When I refreshed the page, I received the following error: Uncaught
   SyntaxError: Unexpected identifier

   5. I then displayed the minified file and saw it had some of the fake
   functions still in the file.

   test8=function(){console.log("THIS IS JUST HERE TO CHECK THE MINIFY
   PROCESS");}
   test9=function(){console.log("THIS IS JUST HERE TO CHECK THE MINIFY
   PROCESS");}
   test10=function(){console.log("THIS IS JUST HERE TO CHECK THE MINIFY
   PROCESS");}
   test11=function(){console.log("THIS IS JUST HERE TO CHECK THE MINIFY
   PROCESS");}
   logOut=function(confirmed,where){if(!confirmed){confirmAction("Log out
   on...",logOut,"logOut");return;}
   var
   params={};params.action="logOut";params.where=where;$.post(WEBSITE_URL,params,function(data,status,ajax){var
   result=JSON.parse(data);logElapsedTime(result.elapsedTime,params.action);if(result.result=="burp"){authorize();}
   else
   if(result.result=="success"){$("html").animate({"background-size":"0%"},{duration:600,complete:function(){location.reload();}});if(SPONSORED&&!HIDE_SPONSOR){$("#div_sponsor").fadeOut();}}});};

   6. I closed and reopened the non-minified version of the file, and
   confirmed that those lines were no longer in the non-minified version of
   the file.

   7. I then added a new line to the top of the file and saved it again
   (with minify set to automatic).

   8. I then refreshed the webpage. Same error and the same deleted lines
   were still included in the minified version.

   9. I repeated the process of making minor changes three times. Same
   error each time.

   10. I then deleted the minified file, refreshed the web page, and it
   worked.

   11. I then repeated the entire process from scratch by adding a new
   round of fake functions, saving, etc.

   12. As occurred in the first round, the error only appeared when I
   removed the functions. I can't remember whether that has been the case in
   real use.

   13. In the second round, I downloaded the minified file to check its
   content in a local editor, just in case my server wasn't delivering the
   proper file or in case the browser had a previous version in its cache. The
   downloaded minified file contained fake functions that should have been
   removed.

   if(SPONSORED&&!HIDE_SPONSOR){$("#div_sponsor").fadeOut();}}});};unction(){console.log("SECOND
   TEST OF MINIFY FUNCTION");}
   test10=function(){console.log("SECOND TEST OF MINIFY FUNCTION");}
   test11=function(){console.log("SECOND TEST OF MINIFY FUNCTION");}
   Notice how a fragment of one of the first ghost fake function is
   appended to an earlier legit function, whereas the others are preceded by
   line breaks.

   I wanted to go through this extra step to make sure my PHP code wasn't
   misbehaving. On my site, in order to allow files to be cached, while
   ensuring that the latest version of any script or style file is always
   loaded, I use the following code:

   $scriptFile = file_exists("code/script.min.js") ? "code/script.min.js" :
      "code/script.js";
   $version = max(array(filemtime("code/server.php"),
      filemtime($scriptFile), filemtime("code/style_1.min.css"),
      filemtime("code/style_2.min.css")));
   $fileAddendum = "?v={$version}";

   With this technique, the update of my primary script or either of two
   style files causes all files to be reloaded when a user returns to the
   site. I included the possible absence of the minified script file because I
   didn't want to continue to manually delete the minified .js file during my
   testing. By the way, there are no problems with modifying the .css files.

   Anyhow, that's why I wanted to download the minified script file to
   verify its actual constent.

   14. I then downloaded the original script.js file — made easier by your
   update (thank you) — to confirm that the deleted lines were in fact
   deleted. They were.

I hope this helps.





<http://LucidQuotes.com>

**Comment by adamjimenez** [comment]
I've tried recreating this with a small file. When I make changes to the main file and save it I can see the changes in the minified file. I'm not seeing wrongly retained code.

**Comment by adamjimenez** [comment]
the next update will use uglifyjs for minifying which should work better.

**Comment by mpmw** [comment]
Since I'm always and to resolve it by manually deleting the previous
minified file, what would you think about ShiftEdit explicitly pre-deleting
the minified file before creating a new one? If you want to temporarily try
that, I can test it out.

**Comment by adamjimenez** [comment]
I've pushed a new update that uses uglifyjs, let me know how you get on.

**Comment by mpmw** [comment]
Seems to work but it's slow. 7 to 8 seconds to save the file (about 1
second for the non-minified file, the rest for uglify), as opposed to a
total of 2 to 3 seconds previously.



<http://LucidQuotes.com>

**Comment by adamjimenez** [comment]
There are a couple of reasons for this. The minification is now being done client-side. Also uglifyjs is better at understanding JavaScript which makes it more effective and safer to use at the cost of speed.  It might be better to disable the auto-minifying and instead manually go to "File -> Save with minified" when you are ready to build the minfied version.

**Comment by adamjimenez** [comment]
Or I could speed up minifying by disabling many of the uglifyjs options for optimising code. There's a trade off between smaller files vs compilation time.

**Comment by mpmw** [comment]
Makes sense. That's what I have been doing (at least for my mega script).

By the way, it does a much better job of compression. A couple days ago, I
reported that the original file was 369KB and reduced to 305KB. Today's
file sizes are 370KB for the original and 248KB for the uglified. That's a
significant difference.

By the way, I'm not sure if this is intended behavior for saving in
general: The tabs use an asterisk to indicate whether a file has been
changed, but the Save command re-saves no matter what. Didn't know whether
you did that just to be safe.

p.s. Thank you for giving me an excuse to get a faster machine. It's not an
easy justification for me to muster with a Chromebox, given how much I
depend on online tools, but if uglify needs additional local processing
power, then who am I to argue?





<http://LucidQuotes.com>

**Comment by mpmw** [comment]
Maybe that's a worthwhile customization setting. At some point, I'll be
able to test it with shorter scripts. I realize that my mega-script might
be bigger than most people use.

What would be really cool (but I'd understand if you didn't want to do it)
is if the save icon in the toolbar had an adjoining save-minified icon.

Also, as noted in my last response, you have given me a nice excuse to get
a faster machine. Perhaps that will make a difference. A few seconds wait
is fine wait. Several makes it inconvenient when I'm chasing UI bugs, since
I'm constantly making a change and quickly refreshing the browser.





<http://LucidQuotes.com>

**Comment by adamjimenez** [comment]
> the Save command re-saves no matter what.

That is intentional. Sometimes you know a file has changed on the server and you need to re-save.

> Thank you for giving me an excuse to get a faster machine

I tested with an 18000 line file and it still took a while to crunch on my desktop i5. So I'm not sure if it will make a huge difference :(

> What would be really cool (but I'd understand if you didn't want to do it)
is if the save icon in the toolbar had an adjoining save-minified icon.

That would mean finding a new icon. Or I could make it shortcut-able..

> Several makes it inconvenient when I'm chasing UI bugs, since
> I'm constantly making a change and quickly refreshing the browser.

I work with uncompressed files while I'm testing and then minify at the end when I'm ready to deploy.

**Comment by mpmw** [comment]
Makes sense on the save.

Oh well. I just closed the Dell website.

A shortcut would definitely work.

I use a git repository to push from the dev site and pull into production,
so I just need to find a surefire way to make sure I don't forget to create
a new minified version while leaving an older one on the production site.



<http://LucidQuotes.com>

**Comment by adamjimenez** [comment]
Could use a pre-commit hook to minify your files.

**Comment by mpmw** [comment]
That's a really good idea. Thanks for suggesting it.



<http://LucidQuotes.com>
