### ISSUE TITLE
GoFish - text added to password when trying to save new site creds

### ISSUE THREAD

**Issue by anneallen** [adamjimenez/shiftedit#214]
When adding a new site, add the creds (ip, username, password) press connect - get "connection OK" but when press save, the valid password is replace with "gofish"

Alarming. Are the creds being phished at this point. If the new site infor is saved, without checking connection first, it works

**Comment by adamjimenez** [comment]
You may have a browser extension that is interfering. Try disabling extensions or running from an incognito window.
