### ISSUE TITLE
Display problems with Tree View when code editor is full screen

### ISSUE THREAD

**Issue by mpmw** [adamjimenez/shiftedit#217]
The enclosed zip walks through the following sequence:

1.  Code window not full-screen. — Everything fine.

2.  Code window full-screen. — Everything fine.

3.  Tree View displayed using Ctrl \ — Does not appear the first few times of pressing the shortcut. When it does, it appears in the bottom panel, which would be okay if expanded.

4.  Tree View hidden with keyboard shortcut. — Notice remaining spacing on bottom and the offset of the zoom trigger in the upper right.

5.  Tree View shortcut pressed again. — One line of the view appears in the bottom panel.

[screenshots.zip](https://github.com/adamjimenez/shiftedit/files/536990/screenshots.zip)

**Comment by adamjimenez** [comment]
Thanks for the report.
I have a fix for this which works by automatically switching out of full screen before toggling the tree.
It also fixes the toggle fullscreen shortcut ctrl-shift-f, which of course is now added to the keybinding settings.

**Comment by mpmw** [comment]
Great idea. Just gave it a go. Both work perfectly.



<http://LucidQuotes.com>
