### ISSUE TITLE
Clicking Yes in file overwrite dialog does not save file.

### ISSUE THREAD

**Issue by mpmw** [adamjimenez/shiftedit#219]
Here's the sequence:

1.  I open the PHP log on the server.

2.  I highlight the contents, press delete, and save the empty file.

3.  I execute my code.

4.  I refresh the file (easier with the new keyboard shortcut — thank you).

5.  The content is refreshed and the tab shows an asterisk. **Perhaps not the correct behavior** since the code window and server file contents are, at that moment, in sync.

6.  I want to clear the file, so I highlight the text, press delete, and press Ctrl S. This time, ShiftEdit warns me that the file has changed on the server, but it really hasn't at this point. 

7.  I press "yes" to overwrite. The content is **not** saved (as remains indicated by the asterisk). I need to initiate save a second time.

**Comment by adamjimenez** [comment]
Thanks, I appreciate the detail you put into these reports. It makes it much easier to locate the problem.

**Comment by mpmw** [comment]
My pleasure. I was worried that I was overloading you with submissions.

I try to provide as much detail as I hope to receive on our products. We're
testing one now. One of the testers has been writing technical
documentation for decades. Two days ago, she wrote: "It doesn't work. The
links do nothing." There's nothing I can do with feedback like that. I
don't know what she's saying doesn't work, what not working means, or what
links she's talking about.






<http://LucidQuotes.com>

**Comment by adamjimenez** [comment]
Exactly, where to start unless you click every single damn link.
