### ISSUE TITLE
Suggestion: Slightly modify right-click behavior on tabs.

### ISSUE THREAD

**Issue by mpmw** [adamjimenez/shiftedit#222]
The current right-click behavior feels a little unpredictable. The slightest variation in pointer position or mousedown and up length, either result in selecting the tab or opening a new tab (since "new" is the first item in the menu). I think it might be because the menu appears too close to the pointer location, making it too easy to inadvertently activate the first menu item.

Suggestions: 
1.  Give a little more distance between the cursor and the menu frame.
2.  Consider only activating/selecting tabs on left-click, so that right-click and right-mouse-down always just display the menu.
3.  Add a menu to the New tab trigger. It could be the first few customized Create items. That way, someone could directly add the tab/file type of their choice.

**Comment by adamjimenez** [comment]
1. At present the menu position is consistent with what I see in OS behaviour.
2. The right click action is consistent with what I see in OS behaviour
3. I'm undecided about this.  Navigating submenus can often be a pain, but it does remove a click. Most of the time I create the file in the tree first but that may just be me.

**Comment by mpmw** [comment]
I understand the consistency, but it's not operating as I believe you would
want. Unfortunately, my screenshot mechanism doesn't include the pointer.
Nevertheless, if you look at the enclosed screenshot, sans pointer, it's a
snap of the menu when I hold down the right-mouse button. The edge of the
pointer is where you would imagine: left side of arrow aligned with left
side of menu, and tip of arrow aligned with the top edge. Because the first
menu item isn't highlighted, you would expect that if I released the mouse
button, that the menu would close without action. That's not what happens
on my machine. If I release the right button, a new window opens.





<http://LucidQuotes.com>

**Comment by adamjimenez** [comment]
Seems ok for me in Windows, I wonder if it behaves differently in ChromeOS.
I can't see the screenshot..

**Comment by mpmw** [comment]
Precision is tough, these days, as the various OS's attempt to display a
variety of font sizes and magnification/page zoom levels while
accommodating the precision of optical mice. In the menu case, at least on
my system with its current settings, the visual feedback doesn't always
represent the true pointer location.

The only thing the screenshot shot showed, since I didn't capture the
pointer, is that the first menu ("New...") wasn't highlighted, but was
still executed when I released the mouse button. That's what keeps throwing
me because I'm still in the habit of refreshing by right-clicking, even
though I have a keyboard shortcut. If I don't remember to use the shortcut
or right-hold and slide, I get a new tab. I suspect that offsetting the
menu by a few pixels (or whatever the lack of precise display feedback is)
will take care of it.







<http://LucidQuotes.com>
