### ISSUE TITLE
Unable to change font size

### ISSUE THREAD

**Issue by joelro** [adamjimenez/shiftedit#224]
When using ShiftEdit I am unable to change the size of the default font in the editor.  When I change the font size in the preferences window it has no effect.  This is the case when using ShiftEdit on Linux Ubuntu 16.04 and on ChromeOS.  Any suggestions would be helpful.

**Comment by adamjimenez** [comment]
Tested on my crhomebook (v53) and worked ok. I wonder if ubuntu issue is to do with not having ubuntu mono installed.
