### ISSUE TITLE
Consistent use/style of ellipsis. 

### ISSUE THREAD

**Issue by mpmw** [adamjimenez/shiftedit#227]
The toolbar menu items have a three-dot ellipsis, while the hamburger site menu items only show two dots.

If you're following the convention that any item resulting in a window receives an ellipsis, then the following menu items would qualify:

- File | Upload
- Edit | Keyboard Bindings
- Edit | Preferences
- All of the items in Help
- Hamburger's Share Site

**Comment by adamjimenez** [comment]
Will go with three dots.
Preferences is a tab instead of a dialog, as are some of the help items.

**Comment by mpmw** [comment]
Great.

Make sense. I've always gone with the convention that anything that opens
another panel, window, or whatever gets an ellipsis, not because users need
to know that, but because of the other side: It lets them know an action
isn't dangerous. But I do know that most go with the dialog rule.





<http://LucidQuotes.com>

**Comment by adamjimenez** [comment]
I've been going with what I interpret from chrome e.g. Settings has no ... - presumably because it opens a tab.

**Comment by mpmw** [comment]
Makes complete sense. It's really just about consistency.





<http://LucidQuotes.com>

**Comment by mpmw** [comment]
Servers.. and Import.. still missing third dots.
