### ISSUE TITLE
Terminal feature conveniences

### ISSUE THREAD

**Issue by mpmw** [adamjimenez/shiftedit#228]
The terminal feature is great. Some thoughts...

1. It would be nice if there was some way to match the currently open site to the desired terminal. For instance, if the site name matches a terminal's name, that terminal could be the default item in the dropdown. If I'm editing documents on Site A, there's a really good chance that I want Site A's terminal.
2. The terminal font is smaller than the tree view's. It would be nice if its size could be independently set or at least be the same.
4. Currently, when you exit from the terminal by typing "exit", you're left with a functionless tab that has to be manually closed. Then to open another terminal, you have to click the New tab. Might be nice if a closed connection results in a list of terminal connections using the latest mechanism you have in the New tab (i.e., with the terminal connections listed) or if you displayed the new tab.

**Comment by adamjimenez** [comment]
1. If using SFTP you can right click a directory and SSH straight in.
2. It will be the same font size as the tree in the next update.
3. Closed connections showed a blank tab. I've changed it to retain what was there and prompt to reconnect or choose a new session.

**Comment by mpmw** [comment]
Nice.
