### ISSUE TITLE
New tab thoughts

### ISSUE THREAD

**Issue by mpmw** [adamjimenez/shiftedit#229]
Love the new design, especially with the boxes. 

A few thoughts...

1. It's a bit confusing that the far right panel (number 3 of 3) and the bottom panel default to a New tab that only shows Tools. That would make sense if documents could not be displayed in those panels; but since they can, then IMHO the New tabs should be the same everywhere.
2. Since Show Less/Show More can't be dragged, might make more sense if they were just plain text.
3. Would be nice if Show More only appeared when there was more to show.

Related to dragging tabs...

1. Might be nice if you could drag a tab to an edge to automatically open and add it to the associated panel versus first opening the panel and then dragging.
2. Would be nice if Ctrl-drag created a copy of the document in the other panel.
3. If users typically dragged to existing panels, or if the panels opened as suggested above, might be worth considering whether it makes sense to ever show a panel with no tabs versus always showing a New tab if there aren't any open documents.

**Comment by adamjimenez** [comment]
I'm pleased you like the new tab design.
1. I originally had the same tabs everywhere, but the east and south tabs looked squashed and I thought those would predominately be used for the tools so I removed the other options.
2. Not sure about this, they are still clickable after all.
3. Agreed

dragging
1. Agreed
2. Interesting idea, copying and pasting seems sufficient to me though.
3. Yes, I've toyed with the idea of leaving them empty. I favoured keeping them to reduce the number of clicks when opening a terminal for example.

**Comment by mpmw** [comment]
1.
2. Yep, it's right in the middle. It can be clicked but not dragged.
3.

1.
2.
3. It's one of those decisions that I can imagine rethinking over and over.
I could see myself feeling one way one day, and another the next.





<http://LucidQuotes.com>
