### ISSUE TITLE
Bottom of terminal content cut off on last line.

### ISSUE THREAD

**Issue by mpmw** [adamjimenez/shiftedit#230]
![screenshot](https://cloud.githubusercontent.com/assets/19599626/19954051/a4e19ccc-a131-11e6-9088-0c99bba2efb4.png)

**Comment by adamjimenez** [comment]
is this chrome? and was it default zoom?

**Comment by mpmw** [comment]
Yes on Chrome. Size was larger than 100%. (I should have mentioned that.)



<http://LucidQuotes.com>

**Comment by mpmw** [comment]
Fix works perfectly.
