### ISSUE TITLE
Collaboration with non-paying users

### ISSUE THREAD

**Issue by KireniaV** [adamjimenez/shiftedit#238]
What is going on? I meet every week with two friends who don't have the premium version. They can no longer see what I have shared with them. It said their trial has expired. My husband and I also collaborate together. He has the educational account, and when he logged in tonight, only one of the sites I have shared with him shows up. Have the free options been discontinued? The reason I have a premium account is to share projects with these three so that we can practice and test out new ideas together.

**Comment by adamjimenez** [comment]
Collaborators would either need to be on free trial or upgrade to premier.

**Comment by KireniaV** [comment]
Does the free educational account option no longer exist? We have been collaborating together for at least a year now, probably much longer--I believe since 2014. It's the whole reason I have an account!

**Comment by adamjimenez** [comment]
Educational accounts still exist for those that have approved applications. If this is no longer workable for you then email me with your details (adam@shiftcreate.com) and I will cancel your account and refund your last payment.
