### ISSUE TITLE
Free Trial has Expired

### ISSUE THREAD

**Issue by ctdh** [adamjimenez/shiftedit#239]
Whenever I try and Launch I get a revolving popup saying "Free Trial has Expired"
But my account is on a Edition: Standard
The popup disappears the the page shows 
"loading..."
then
"loading strings..."
and then the "Free Trial has Expired" popup appears again and ShiftEdit will not launch

**Comment by adamjimenez** [comment]
You would need an upgrade:
https://shiftedit.net/premier

**Comment by ctdh** [comment]
But I received this email from you last month...

On 15 November 2016 at 13:11, <adam@shiftcreate.com> wrote:

> Your account has been upgraded to Premier Edition.
>
> Refresh ShiftEdit to access the Premier features, including:
>
> * Unlimited sites
> * Revision History (File->Revision History)
>
> If you have any questions please reply to this email.
>
> Thanks for supporting ShiftEdit!
>
> Best Regards,
> Adam Jimenez (Founder of ShiftEdit)


Kind regards,

Charles Hewitt
+44(0)7850 556391

**Comment by ctdh** [comment]
and I have a paypal transaction ID:
Transaction ID: 63H03070GM9067842
<https://www.paypal.com/uk/cgi-bin/webscr?cmd=_view-a-trans&id=63H03070GM9067842>

Kind regards,

Charles Hewitt
+44(0)7850 556391

**Comment by adamjimenez** [comment]
You may be logging in with the wrong account, make sure you are logging in with your gmail account. Please email me directly if you need further assistance: adam@shiftcreate.com
