### ISSUE TITLE
Creating a new site will not read actual path

### ISSUE THREAD

**Issue by frafor** [adamjimenez/shiftedit#240]
1. Create the new site
2. Give it the proper path
3. Call the Shiftedit app
4. Choose new site

It fails! it will reopen a pre-existing site again and again and again. It does not pay attention to the NEW PATH defined in the parameters.

It loads the directory and continues to show that of a previous directory, but not the new one.

**Comment by adamjimenez** [comment]
I'm unable to recreate this, is it possible to provide more info or even a screencast?

**Comment by frafor** [comment]
The problema is difficult to reproduce.

In my case, I have, in one physical server, several sub-directories.

I want my Shiftedit connection to open one specific path.

So, I set as path, the path (how strange) from where the files should open
with that specific connection.

A PHP file to accelerate my accesses is already at the main directory.

If I want to use the fast way (using the php file), then it will not work.
It will open the files from a different path, in spite of the fact the the
php file DOES contain the proper path.

So, I use a regular connection (SFPS), the slow way. Then it works as
expected. However, if I try to use the php boost way (faster access) then,
EVEN THOUGH it shows as the first line the correct path, it OPENS the files
from ANOTHER path.

Here is part of the contents of the php file:

$host = 'localhost';
$username = 'person'; //username or ftp username
$password = 'secret-word'; //password or ftp password
$dir = '/var/ww4/html/direc1/'; //path to files e.g. dirname(__FILE__).'/';
$server_type = 'sftp'; //local, ftp or sftp. local requires webserver to
have write permissions to files.

As you can see, it *should* open at:

*$dir = '/var/ww4/html/direc1/'; //path to files e.g.
dirname(__FILE__).'/';*

But it *does not. *It *does show* the above as the path it is supposedly
using, but it opens the file from a different path.

Incidentally, the path it opens is this:

*$dir = '/var/ww4/html/direc0/'; //path to files e.g.
dirname(__FILE__).'/';*

And such path *used to be *the path of the original (edited) connection.

I can live without the *php* fast functionality, but I really want to be
able to use up to its full capabilities, especially when my time is at
stake.

**Comment by adamjimenez** [comment]
It's tricky to diagnose without seeing the site but here's a clue.
Turbo mode uses the web url to create an ajax connection.
Therefore the web url should match up with the home directory path.
I think it might be hitting the proxy script on your server.

If you want me to figure it out - please email me directly with site details adam@shiftcreate.com
