### ISSUE TITLE
Error 111, connection refused Digital Ocean One Click Django App

### ISSUE THREAD

**Issue by joelro** [adamjimenez/shiftedit#241]
When connecting to a new Digital Ocean Django App, on ubuntu 16.04, I get "Error 111, connection refused, when using the Django user or the root connection.  This error is odd because it is not consistent.  I can see the files in the file explorer, but the error will pop up frequently.  I am using port 22, but have also tried 80 and 443 with the same result.  This is a new installation and no changes have been made to the default server configuration other than an "apt install update && upgrade" as soon as the server was up and before attempting to connect from ShiftEdit.

**Comment by adamjimenez** [comment]
If this is still occurring and you'd like me to investigate, please email the connection details to adam@shiftcreate.com
