### ISSUE TITLE
Unable to connect to ftp server which uses cloudflare cdn..

### ISSUE THREAD

**Issue by vaibhav011286** [adamjimenez/shiftedit#242]
Hello,
one of my domain have enabled cloudflare cdn, so for this such domain I unable to access ftp either but normal ftp or SFTP... it just showing login incorrect...
And with same login info I able to login via codeanywhere.com using sFTP...

Please, help me..

**Comment by adamjimenez** [comment]
Hi Please email details to adam@shiftcreate.com so that I can investigate.
