### ISSUE TITLE
Not working with Amazon and Git (Bitbucket)

### ISSUE THREAD

**Issue by computer-spezialisten-de** [adamjimenez/shiftedit#243]
I creat a new account using git and amazon.
When i try to open the project i got this error:
-----------------
Cannot connect to xxxx.yyyy.shiftedit.io:22. Error 0. php_network_getaddresses: getaddrinfo failed: Name or service not known

Can't connect with key
-----------------
my account is: computerspezialisten

**Comment by adamjimenez** [comment]
I've recently updated the cloud server integrations. Make sure you are on the latest version (18.6.43) and try again.
