### ISSUE TITLE
ShiftEdit deleting files on save after new Update

### ISSUE THREAD

**Issue by osourcesol** [adamjimenez/shiftedit#246]
Greetings,
I am using Premium ShiftEdit as "asad.89@live.com", after activating new updates, I am getting a horrible issue, when I am saving files it is giving me some error and then delete the file. I have wasted all my code, please check it on first priority. Neither it is creating a file nor modifying them but delete when update any file, I have tried everything such as re-login, page refresh, site re-added etc.

Please check the attached screenshot of the error.
![error](https://cloud.githubusercontent.com/assets/11520313/22858878/c8bb6a42-f0eb-11e6-9460-305eb4734288.png)

**Comment by adamjimenez** [comment]
I'm not aware of an update that would affect this.
Do you have free space on the server? And are you within quota?

**Comment by adamjimenez** [comment]
For FTP if it can't save the file it will try to delete it and then save it again.
This seems to be the only way to save on some FTP servers.
If it can delete the file it should be able to write a new one unless there is some disk space/ quota issue.
