### ISSUE TITLE
JS Lint not working past first error

### ISSUE THREAD

**Issue by wsherliker** [adamjimenez/shiftedit#251]
The JS lint only shows one error and then the next is always 'too many errors' and it stops linting. If you fix the error it shows the next one issue and then again the 2nd is 'too many errors'. This is in Chrome browser.

**Comment by wsherliker** [comment]
Note there is also an error in long files (it is JSHint not JSLint by the way) where it just gives up with the JSHint processing after a certain percentage even though there are no errors shown...

![image](https://cloud.githubusercontent.com/assets/1018839/24602261/f24a0348-1853-11e7-8dcf-afb425de6c45.png)

**Comment by adamjimenez** [comment]
I'm looking to move to eslint

**Comment by wsherliker** [comment]
OK - it is a big pain for me personally, not sure about other users too. Any updates on this please do keep me posted. It makes it a less than ideal JS editor.

**Comment by adamjimenez** [comment]
switched to eslint - let me know how it goes
