### ISSUE TITLE
Logon Array Error

### ISSUE THREAD

**Issue by mday1** [adamjimenez/shiftedit#261]
![issue1](https://user-images.githubusercontent.com/31091100/29398482-3a4edb16-82e2-11e7-923d-05141f98a3a7.png)
 I log in > Add Details [fieldentries] > Hit Save > Receive the [issue1] Error

My credentials are correct but my WP site is currently experiencing a syntax error

**Comment by adamjimenez** [comment]
Please try again in the latest version
