### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by abalter** [adamjimenez/shiftedit#264]
I could use some help installing. I tried the simplest approach of just cloning into my web root. When I visit `localhost/shiftedit` it tries to load (I get the loading progress bar). But then a dialog flashes that I can barely read, and the url changes to `localhost/login`.

**Comment by adamjimenez** [comment]
make sure you are logged into the shiftedit website as it should use this to connect to your account.
else check the js console for errors, debug info..

**Comment by abalter** [comment]
Is there any way to self host this?

**Comment by adamjimenez** [comment]
If you want to connect directly to a local server you can use the turbo mode option.
But if the point is just to host it for free then I can't help you with that for obvious reasons.

**Comment by abalter** [comment]
I just mean to self host it to use on my own server. For instance, like ICEcoder, or the Cloud 9 SDK editor. Can I also just run it as a desktop app?

**Comment by adamjimenez** [comment]
Check chrome's JS console for errors.
What would be the benefit of hosting on your own server?

**Comment by abalter** [comment]
Self-hosting a web-based code editor allows you to edit files on your server through your browser. A short list of FOSS examples are:

1. [ICEcoder](https://icecoder.net/)
1. [Cloud9](https://github.com/c9/core)
1. [Codiad](http://codiad.com/)
1. [Eclipse Che](https://www.eclipse.org/che/)

I use ICEcoder quite a bit. But it has some quirks I don't like, and I wanted to try out ShiftEdit.

**Comment by adamjimenez** [comment]
You can already edit files on your server using ShiftEdit.
SE is not FOSS (neither is C9 btw).

**Comment by abalter** [comment]
Sure, that makes sense. There is nothing wrong with having a commercial product! 

For my purposes, because I want to easily edit code on a variety of servers (including the WSL on my laptop), it makes more sense to install an instance of an editor behind apache or nginx or whatever in my own webspace.

If it's not a good fit, it's not a good fit. No criticism.

**Comment by adamjimenez** [comment]
Using our service to log into multiple servers is a lot more convenient than installing on multiple servers.
