### ISSUE TITLE
Errors on connect to dropbox

### ISSUE THREAD

**Issue by tbirnseth** [adamjimenez/shiftedit#265]
After authenticating on Dropbox, get the following error after Choosing the path and Save.
{"error_summary": "path/malformed_path/.", "error": {".tag": "path", "path": {".tag": "malformed_path"}}}
Dir does not exist: /work/1st Source IT/Projects/WebSites/dev4/

**Comment by adamjimenez** [comment]
Please try now, this is fixed.
