### ISSUE TITLE
AJAX FTP broken

### ISSUE THREAD

**Issue by stepresearch** [adamjimenez/shiftedit#285]
The latest update release today, 3/16/2018 sometime after noon eastern, has broken the ajax based FTP connection.

Now always receiving this error:
Server type not supported: AJAX

**Comment by stepresearch** [comment]
Note, the problem occurred after we saw the popup to go to the latest version and we said yes.

Happening with all our developers.

**Comment by adamjimenez** [comment]
Resolution was to edit the site and press save.
