### ISSUE TITLE
Undo and redo buttons on editor toolbar not working

### ISSUE THREAD

**Issue by JeremyBackus** [adamjimenez/shiftedit#286]
You can still undo and redo with Ctrl+Z or Ctrl+Y, but the buttons on the editor toolbar never become active.  It looks like it is like this in Dev and Stable for me in Chrome.  I tried on a couple of FTP connections and  I also tried clearing the app cache and still get the same behavior.

**Comment by adamjimenez** [comment]
This is fixed in the dev update.
It only happened for shared sites.
