### ISSUE TITLE
Error 110 : connection timed out

### ISSUE THREAD

**Issue by bloodfiend** [adamjimenez/shiftedit#290]
I keep getting a "connection timed out" error, and I know my connection is fine, if this could be fixed everything else seems fine and I would like to continue using your software.

**Comment by adamjimenez** [comment]
Check you're using the correct port and that our ips are not blocked. You
can increase the timeout in advanced settings.

**Comment by bloodfiend** [comment]
I increased the timeout limit. It still does it. This only happens half of
the time, and it always seems to happen when I'm doing important work. I
have changed passwords and I am pretty sure everything is gucci on my end.
After i get the timeout/incorrect login i wait a few minutes and then
refresh the page. Most of the time it will reconnect, but then after
navigating a few folders it will stop and give me the error. I habe changed
files and have seen them change on my businesses website, so I know I am
connected.

**Comment by adamjimenez** [comment]
Try either whitelisting our ips. Or if your server supports PHP then enable
turbo mode.

**Comment by bloodfiend** [comment]
I jumped into Turbo mode, and it seems to working flawlessly for this small
work I am doing. I am going to be working on some updates tonight and if
all goes well you have yourself another subscriber. Thanks for your timely
responses and help.

**Comment by adamjimenez** [comment]
Thanks!
