### ISSUE TITLE
Is there a list of known IP addresses for ShiftEdit?

### ISSUE THREAD

**Issue by williamsdb** [adamjimenez/shiftedit#291]
Not a bug but would be useful to know if there is a fixed set of IP addresses that ShiftEdit comes from. I block access to my server to known IP addresses, would be good to add SE to that white list.

**Comment by adamjimenez** [comment]
From [the docs](https://shiftedit.net/docs/troubleshooting)

> 54.235.66.128
> 54.204.38.137
> 54.197.226.18
> 
> To allow SSH terminal connections, our IP is:
> ssh.shiftedit.net [50.116.56.24]
