### ISSUE TITLE
Upload by URL not working

### ISSUE THREAD

**Issue by JeremyBackus** [adamjimenez/shiftedit#296]
Upload by URL (to FTP) does not seem to be working.  I actually noticed this earlier today, but I just tried again and it's still not working.  The file is created, but it's empty.

Here are some files I've tried to upload:
https://code.jboxcdn.com/plugins/Notice/jBox.Notice.js
https://code.jboxcdn.com/plugins/Notice/jBox.Notice.css
https://code.getmdl.io/1.3.0/material.cyan-light_blue.min.css

**Comment by adamjimenez** [comment]
fixed
