### ISSUE TITLE
Emmet

### ISSUE THREAD

**Issue by adamjimenez** [adamjimenez/shiftedit#30]
Get emmet working.

**Comment by mjhd** [comment]
Please get emmet working!
Ctrl+E & Tab+E do nothing!!
Windows 8.1 -> G. Chrome

**Comment by adamjimenez** [comment]
Got this working in 17.0.13.
BTW the shortcut is alt+e or tab

**Comment by mjhd** [comment]
Gracias!!

Realized I was having a browser issue anyway :D
