### ISSUE TITLE
cannot open existing text files on GSuite

### ISSUE THREAD

**Issue by maanku** [adamjimenez/shiftedit#300]
Hi,

I purchased the subscription after the evaluation expired (some time ago). When I've attempted to open Drive documents, the editor perpetually loads the tiny file and never completes. That is, it shows "Opening 2k5uh4235ikuh42iouy" and the tab text will change regularly to show activity but nothing ever renders.

Creating a new file while in that screen will "work" but when I save the file, it does not save to the Drive and I'm not sure where it is successfully saving the file to.

The Drive window in the selection frame also does nothing. Any suggestions in how to isolate the issue?

Thanks

Attempting to open the small file listed in the second screenshot:
![screenshot 12](https://user-images.githubusercontent.com/17717215/39069045-12cca378-44a4-11e8-9be2-43b3674aa6af.png)

One of the small files that will not open.
<img width="632" alt="screenshot 13" src="https://user-images.githubusercontent.com/17717215/39069140-7c566658-44a4-11e8-885a-367dac7282d6.png">

**Comment by maanku** [comment]
Update: The issue corrected itself just by waiting until today. I will guess that since nothing else worked, there may have been some issue with my entitlement from the purchase being processed quickly.

**Comment by adamjimenez** [comment]
If this happens again please check the console output ctrl-shift-j
