### ISSUE TITLE
Beautify does not work

### ISSUE THREAD

**Issue by wsherliker** [adamjimenez/shiftedit#302]
Hi,

You have updated the beautify functionality again and again it really does not work. HTML and JavaScript do not beautify. It just puts HTML into a single line with random spacing. JavaScript it removes spaces between keywords, breaks the code and makes it look worse than before the beautify.

Just reference:
http://jsbeautifier.org/
and
https://www.cleancss.com/html-beautify/

They do the job as did your old beautifier code. Please stop changing it!

**Comment by adamjimenez** [comment]
The problem with jsbeautify is that it does not handle mixed modes well at all which Is why I made my own.
If you can give me a few simple test cases I will look into fixing them.

**Comment by wsherliker** [comment]
Any HTML causes issues to be honest. But as an example use this:
<div class="homePage"><img alt="Header" src="https://support.domain.co.uk/view.image?pane=Header&amp;panename=Header" title="Header" data-runat="server" data-template_pane="1" data-paneid="Header" data-panedescription="" />
<div class="unit1 header">
<div class="centreWrap"><header class="unit1 mainHeader">
<div class="unit1">
<div class="logo"><a href="http://domain.co.uk/"><img alt="Monterverdi logo" height="38" src="/image/template2018/pageimages/http___domain.co.uk_images_logos_monterverdi-logo.svg" width="224" /></a></div>
<div class="searchForm"><a href="http://domain.co.uk/media-assets">Login</a></div>
</div>
<nav class="unit1" id="navWrap"><img alt="MainNav" src="https://support.domain.co.uk/view.image?pane=MainNav&amp;panename=MainNav" title="MainNav" data-runat="server" data-template_pane="1" data-paneid="MainNav" data-panedescription="" /></nav></header></div>
</div>
</div>
<div class="unit1">
<section class="centreWrap"><header class="unit1 pageTitle"><img alt="PageTitle" src="https://support.domain.co.uk/view.image?pane=PageTitle&amp;panename=PageTitle" title="PageTitle" data-runat="server" data-template_pane="1" data-paneid="PageTitle" data-panedescription="" /></header>
<div class="unit1 shopNavBar">&nbsp;</div>
<div class="unit1 mainContent flexbox padding">
<div class="unit4"><img alt="10" src="https://support.domain.co.uk/view.image?pane=10&amp;panename=10" title="10" data-runat="server" data-template_pane="1" data-paneid="10" data-panedescription="" /></div>
<div class="unit3-4"><img alt="4" src="https://support.domain.co.uk/view.image?pane=4&amp;panename=4" title="4" data-runat="server" data-template_pane="1" data-paneid="4" data-panedescription="" /></div>
</div>
</section>
</div>
<section class="unit1 greyBg">
<div class="centreWrap padding">
<div class="unit1">
<div class="unit2 socialMedia">
<h2><strong>Join us</strong> on social media</h2>
</div>
<div class="unit2 newsletter">&nbsp;</div>
</div>
</div>
<footer class="centreWrap padding"><img alt="Monterverdi" class="logo" src="/image/template2018/pageimages/http___domain.co.uk_images_logos_monterverdi-logo-black.svg" /><hr /><a href="http://domain.co.uk/support-us"><img alt="Support us" class="support" src="/image/template2018/pageimages/http___domain.co.uk_images_graphics_support-us.svg" /></a>
<ul>
<li><a href="http://www.domain.co.uk/contact">Contact</a></li>
<li><a href="http://www.domain.co.uk/privacy-policy"> Privacy Policy</a></li>
<li><a href="http://www.domain.co.uk/vacancies"> Vacancies</a></li>
</ul>
<p><strong>Level 12, 20 Bank Street, Canary Wharf, London E14 4AD, UK<br />Tel: +44 (0)20 7719 0120 <span>|</span> Email: <a href="mailto:info@domain.org.uk">info@domain.org.uk</a></strong><br />Charity registration no. 272279 <span>|</span> Company registered in England no. 1277513 <span>|</span> VAT no. 241 7853 56<br />
<script type="text/javascript">// <![CDATA[
document.write(new Date().getFullYear())
// ]]></script>
&copy; The domain Choir and Orchestras Limited</p>
</footer></section>
<p><img alt="Footer" src="https://support.domain.co.uk/view.image?pane=Footer&amp;panename=Footer" title="Footer" data-runat="server" data-template_pane="1" data-paneid="Footer" data-panedescription="" /></p>

**Comment by adamjimenez** [comment]
I've pushed a fix that should help with this. Remember to use the insert code button when pasting into github.

**Comment by wsherliker** [comment]
Thanks that now works - it's not a perfect beautify but a lot better.

**Comment by wsherliker** [comment]
Closing ticket.
