### ISSUE TITLE
Suggestion: create manifest.json

### ISSUE THREAD

**Issue by VitoAballay** [adamjimenez/shiftedit#308]
Hi! It would be great if a manifest.json file were included in ShiftEdit, to use it as a web application on Chrome mobile in full screen.

Something like this:
`{
	"name": "ShiftEdit IDE",
	"short_name": "ShiftEdit",
	"icons": [{
		"src": "favicon-192.ico",
		"sizes": "192x192",
		"type": "image/png"
    },{
		"src": "favicon-152.ico",
		"sizes": "152x152",
		"type": "image/png"
    },{
		"src": "favicon-120.ico",
		"sizes": "120x120",
		"type": "image/png"
    },{
		"src": "favicon-76.ico",
		"sizes": "76x76",
		"type": "image/png"
    }],
	"theme_color": "#ffffff",
	"background_color": "#ffffff",
	"start_url": "https://shiftedit.net/home",
	"display": "standalone",
	"orientation": "portrait"
}`

Thanks!

**Comment by adamjimenez** [comment]
Thanks, this is done!
