### ISSUE TITLE
Error parsing file ... not a constructor

### ISSUE THREAD

**Issue by dougalx** [adamjimenez/shiftedit#309]
Upon saving a JS file to an FTP server:

`Error parsing file: (intermediate value)(intermediate value)(intermediate value) is not a constructor`

I just saved this file a few times and it worked fine, but then I get this message and can't upload unless I refresh ShiftEdit

**Comment by adamjimenez** [comment]
Is it reproducible?
Likely to be code dependent..

**Comment by adamjimenez** [comment]
I need steps to reproduce this. Closing.

**Comment by adamjimenez** [comment]
dupe of #304
