### ISSUE TITLE
Suddenly shiftedit is taking longer than usual doing anything

### ISSUE THREAD

**Issue by frafor** [adamjimenez/shiftedit#322]
Be it **save** a file, old or new, large or small, it is not only taking really long, but it *freezes* the interface and nothing else can be done.

Trying to go from top to bottom in a file has become a heavy event: it will start moving in bursts, but not in one single jump.

And when typing, it has **really** become a slow process (PHP or JS file).

**Comment by adamjimenez** [comment]
Which browser and ShiftEdit version are you on?

**Comment by frafor** [comment]
Browser: Chrome Versión 68.0.3440.106 (Build oficial) (64 bits)
ShiftEdit: Version: 19.0.45
Edition: Basic ...

**Comment by adamjimenez** [comment]
Does the problem persist in the dev version?
https://shiftedit.net/update-details

**Comment by frafor** [comment]
Yes, it persists in the dev version.

My 4201-line php file makes little jumps when I type control-End or control-Home, instead of going directly to the first or last line and only showing the first or last page.

Page-Up and Page-Down are behaving just as jumpy or worse, because they make from 4 to 6 jumps from page to page.

Typing on any file has become a hassle: typing has become a slow motion process, even typing text inside a comment (// o /*  */).

Of course, this did not use to happen in the past.

**Comment by adamjimenez** [comment]
Can you try in an incognito window to rule out browser extensions?
Does disabling autocomplete make a difference?
Is it a low power computer?

**Comment by frafor** [comment]
In incognito window, it is just as slow (maybe even slower... can't say)

Control-END control-Home, with or without autocomplete, take a long time.

The computer is rather powerful: 15 GB of RAM, 256 GB Solid state disk drive. Cpu

Watch how the CPU goes up by moving keys (control-home and control-end).

![usocpushiftedit](https://user-images.githubusercontent.com/4719577/44318384-3bc9cd80-a3fb-11e8-800b-44be1cb7c2ca.JPG)

Take a look at how powerful the pC is:

![mypcpower](https://user-images.githubusercontent.com/4719577/44318457-a7ac3600-a3fb-11e8-9395-52fd8e7d5047.JPG)

Everything else, except ShiftEdit, flies!!!

**Comment by adamjimenez** [comment]
Does disabling autocomplete make a difference?

**Comment by frafor** [comment]
Nothing made a difference. Nothing. I am using a local editor and sending files by ftp now. But I do not want to continue like that forever. Also, when I save a file, it takes FOREVER for the control of the program to be available again.

**Comment by adamjimenez** [comment]
Does it happen in firefox?
It could be a preference option or you could try re-creating the site.
It's strange as it's the only report of this and there haven't been any changes I can think of that would cause this.

**Comment by frafor** [comment]
Bingo! In the iPad (a very old one, slow in almost anything) Shiftedit in the same file under Chrome for iPad, did move without the jumps, and typing text is just as slow as Chrome is regularly under this iPad. So, what next? I have tried closing all apps or windows programs and using only Edge with Shiftedit, and the slowness is there immediately.

**Comment by adamjimenez** [comment]
If you create a new file is it still slow?
Or is it just for existing files?
Do you have norton internet security or anything like that, that could be interfering?

**Comment by adamjimenez** [comment]
I have a similar setup win10 64, chrome 68 and have no performance issues.

**Comment by frafor** [comment]
Touching HOME from the bottom or END from home, causes 5.6% of 4 cpus and 8 logical cpus to be in use for the Chrome task (15 GB of RAM!). 3.7% to open site; 5.2% to open tree first part; 7.8% to open large tree branch.

Edge: 9.4% to expand tree. Same file: 5.2% to open large file; 2.3% from top to bottom (opposed to 5.6% in Chrome), AND taking less than 1 second.

However, Edge takes less time (uses more CPU) than Chrome (uses less CPU but takes longer). Also, Edge is not multi-thread (?) but I will not be using Edge for anything but Shiftedit.

So, conclusion: Chrome has a problem:

Google Chrome is up to date
Version 68.0.3440.106 (Official Build) (64 bits)

**Comment by adamjimenez** [comment]
We're on the same chrome version. Mine also hits 5% cpu when pressing home but only for a fraction of a second so that looks normal. Mine shows as using 251MB in memory footprint.

You could... go into Chrome dev tools (F12).
On the performance tab press record and then go back to shiftedit and press home/ end.
Then stop the record and then dig into the call tree to see what's taking the most time.

see screenshot:

![image](https://user-images.githubusercontent.com/573192/44481315-6014ec80-a63d-11e8-853c-37b05b6d5e94.png)

**Comment by frafor** [comment]
Here is the problem:

[image: image.png]

That is what happens in Chrome after I hit TOP being at the bottom of a
4200-line file. 11 bursts, instead of one movement. Then, see this:

[image: image.png]

grey area 8211.9 ms (other). Why is that? Chrome needs to do "something"
before it continues to move the file upwards? (or downwards?) What a
hassle! I just need my time!

**Comment by adamjimenez** [comment]
images not showing..
I just pasted my image into the github comment field.

**Comment by frafor** [comment]
Good news! Version 69. (Chrome) has solved the problem.

There was a scrolling problem, reported in several Internet forum sites discussing hundreds of issues.

The new Chrome version brought about other new issues, but one can work with it.

**Comment by adamjimenez** [comment]
Great!
