### ISSUE TITLE
Can't delete a Custom server

### ISSUE THREAD

**Issue by thomaswwp** [adamjimenez/shiftedit#327]
New tab 
> Tools Panel
> Servers
Select a server with - Custom after it e.g. **mycustomserver - Custom**
Click [Remove]
Click [Yes]
Message received: 
**Error
Provider not recognised: Custom
[OK]**

**Comment by adamjimenez** [comment]
fixed

**Comment by thomaswwp** [comment]
Confirmed. Thank you.
