### ISSUE TITLE
Incorrect bottom links on shiftedit.net

### ISSUE THREAD

**Issue by jfkz** [adamjimenez/shiftedit#33]
Hi, man, first of all I have to say that you made an amazing editor!
But on the bottom I found 2 broken links: Merchandise and Google Groups.

**Comment by adamjimenez** [comment]
Thanks!

Alas the merch is no more, I will remove the link for that.
Google group link works ok for me.

On 14 November 2015 at 20:28, Mike <notifications@github.com> wrote:

> Hi, man, first of all I have to say that you made an amazing editor!
> But on the bottom I found 2 broken links: Merchandise and Google Groups.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adamjimenez/shiftedit/issues/33>.
>



-- 
Best regards,
Adam Jimenez

**Comment by jfkz** [comment]
Ok. I have checked again Google group link and now it is working. Magic =)
Thanks for your work!

**Comment by jfkz** [comment]
Ok. I have checked again Google group link and now it is working. Magic =)
Thanks for your work!

**Comment by adamjimenez** [comment]
fixed
