### ISSUE TITLE
Can't find how to open SSH

### ISSUE THREAD

**Issue by williamsdb** [adamjimenez/shiftedit#331]
According to the documentation to open an SSH terminal "You can SSH to your server by opening the Secure Shell panel at the bottom of the screen."

I have spent ages looking at the bottom of the screen (see below) and cannot find anything that might do that? What am I missing?

![2018-11-27 16-45-21](https://user-images.githubusercontent.com/8099483/49097316-6a5e0c80-f264-11e8-95e2-83387e7d080b.png)

**Comment by adamjimenez** [comment]
sorry that's outdated, it's on the new tab page under tools:
![image](https://user-images.githubusercontent.com/573192/49098591-1e609700-f267-11e8-8f1e-69874adcebfa.png)
