### ISSUE TITLE
JSHint gives up...

### ISSUE THREAD

**Issue by wsherliker** [adamjimenez/shiftedit#333]
When you are editing a JS file and JSHint finds and issue is sometimes shows it. A lot of the time though it shows the very unhelpful:
 [1/1] Too many errors. (37% scanned). on ...

A) this does not detail any errors and when I pass the code through JSHint online it shows no errors
B) It means the code is then not checked

This happens in lots of JS files, usually those over a few hundred lines long but it makes the validation not work.

This together with the HTML/XML/JS beuatified issues make me question if I can continue to use ShiftEdit. The issues above have only come about since the new UI and it is annoying that it is a step back in basic editing functionality rather than a step forward. Understand that you want to rearchitecture etc. but you should not break what was working in the process.

Warren

**Comment by adamjimenez** [comment]
I've updated the dev release so that you can edit the maxerr property under Preferences -> Advanced -> Lint checking
