### ISSUE TITLE
File Manager doesn't always execute menu commands or maintain proper sorting.

### ISSUE THREAD

**Issue by mpmw** [adamjimenez/shiftedit#334]
I cannot determine all the why's and when's, which is why I haven't reported this sooner, but if you try using the File Manager for some quick and extensive file manipulation, you might see some of the issues that I frequently encounter. Specifically:

- There are times when menu actions are ignored. 
- After a file operation (e.g., renaming, duplicating) single files might display out of order: sometimes moved to the top of the list, sometimes the bottom, sometimes just a couple lines away.
- A single click always results in ending the file name — not something many us would want.
- If the single-click-to-open feature is on, right-clicking a file, and then right-clicking another, leaves an odd highlight of the previously selected file or files.

**Comment by adamjimenez** [comment]
I've fixed the odd highlight issue.
Please provide steps to reproduce the other ones in separate issues.
