### ISSUE TITLE
Terminal has problems with line-wrapping

### ISSUE THREAD

**Issue by mpmw** [adamjimenez/shiftedit#335]
I typically use the terminal for Git. Given the depth of the directory structure, even if I close one of the two panels on the left (File Manager and code panel), the terminal needs to wrap lines (e.g., when using commit -a -m to document my edits). During those times, the terminal cursor moves to the left, but it doesn't drop to the next line, so whatever I type gets scrambled with the previous content. When I hit the bottom of the window, it often does not scroll up, so I get the same effect. Recently (I believe) if I hide the terminal panel with the connection open, and then re-open it, my maximum column width drops to several characters. I have to close the tab and re-open the connection.

**Comment by adamjimenez** [comment]
Thanks, this annoying bug is fixed and lines now wrap correctly.
