### ISSUE TITLE
Connection is failing and unclear error message

### ISSUE THREAD

**Issue by ItayBe** [adamjimenez/shiftedit#336]
I am using ShiftEdit for almost a month, working on the same project with the same connection details, without a major connection problems, but today I have got this message for the first time, and the connection is continue to fail again and again:  
**"ftp_rawlist(): php_connect_nonb() failed: Operation now in progress(115)"** 
Please, help me to understand the reason, and how to solve it.
Thanks.

**Comment by adamjimenez** [comment]
This sounds like it could be a firewall issue with the FTP server.
You may need your webhost to whitelist our ips:
54.235.66.128
54.204.38.137
54.197.226.18

If it starts working again, you can try enabling turbo mode in site settings for smoother connections.

**Comment by ItayBe** [comment]
O.k, thank you.
