### ISSUE TITLE
Single click rename

### ISSUE THREAD

**Issue by smdev0925** [adamjimenez/shiftedit#338]
Hi, 

Just a little thing that is becoming irritating. When I click on a folder it always wants to rename it. It seems a single click of a folder or file is enough. Can this be fixed or made less sensitive? Ideally I'd like to see an option to turn this off altogether. Right click->rename for me is adequate.

**Comment by adamjimenez** [comment]
If you have "Single click to open files" in preferences enabled then this rename behaviour is also disabled.

**Comment by smdev0925** [comment]
OK. Is it possible to have an option where nothing happens when you single click? That would be expected file tree behaviour.

**Comment by adamjimenez** [comment]
I need to tweak the default as it shouldn't rename like that on the initial click.

**Comment by adamjimenez** [comment]
This is addressed in dev channel
