### ISSUE TITLE
SSH Remote host identification has changed

### ISSUE THREAD

**Issue by gasparuribe** [adamjimenez/shiftedit#345]
Hi there! Thx 4 the help and this amasing WebApp, i use it for a long time, it used to have a lot of bugs, but now everithing is working smooth like a charm!!! 
Sorry 4 bad english, not my native. There are no typos on the server, just here xP
There is no problem with the sftp, the trouble its when i try to ssh with terminal.

Im not sure why, i believe it used to connect, im almost sure this is something i have to fix in my server, but im kind of lost... the SSH key is in /host/exampleUser/.ssh/authorizedkeys and its the only file in that folder, to debug i copy that file to /root/.ssh/......  this didnt help. There is nothing on /etc/hosts.allow or /etc/hosts.deny (only the info commented with #) (also im thinking to use those files to only allow shiftedit) 
The server its actually a VM (virtual machine), so i also have FULL backups and tried with a olderone that used to work. I know that the issue its or inside the VM or on shiftedit (i doubt it) cause if i try to connect from other computer it knows i only can login whit a key file, not passwords, and it shows my banner.
 The SHA256 is the one of my server, or thats what i think o.O
suggestions?
this is the terminal of ssh display on shiftedit:

`@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!

Someone could be eavesdropping on you right now (man-in-the-middle attack)!

It is also possible that a host key has just been changed.

The fingerprint for the ECDSA key sent by the remote host is
SHA256:[the finguerprint of my server removed for example]

Please contact your system administrator.
Add correct host key in /root/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /root/.ssh/known_hosts:82
  remove with:
  ssh-keygen -f "/root/.ssh/known_hosts" -R "[myexample.com]:22"
ECDSA host key for [myexample.com]:22 has changed and you have requested strict checking.
Host key verification failed.
`

**Comment by gasparuribe** [comment]
Sorry just checking this git page, is this a version i can host myself? (im using https://shiftedit.net dont want to change, just for the doubt...)

**Comment by adamjimenez** [comment]
You might have reinstalled your server which is why it's showing this warning. I've made a change that should allow you to still connect over SSH.
Alternatively you should be able to use a different hostname which points to the same server.
