### ISSUE TITLE
Git message box timeout

### ISSUE THREAD

**Issue by smdev0925** [adamjimenez/shiftedit#349]
Hi, 

Bitbucket is having performance issues today which has highlighted a small thing. In both Stable and Dev I see this. The message box appears to time out without any message. 

![image](https://user-images.githubusercontent.com/16979556/57133823-eb817880-6d9b-11e9-98f1-0524c72a6518.png)

**Comment by adamjimenez** [comment]
I've pushed a fix for this which will indicate if there is a timeout.
