### ISSUE TITLE
After find, focus doesn't go to code view

### ISSUE THREAD

**Issue by tbirnseth** [adamjimenez/shiftedit#351]
Similar to closed issue #198, it's is extremely awkward to have to click into the code view in order to move to the first occurrence of a found phrase.  ctl-k simply clears the browser address bar and generates a drop down of history.

Seems to me that on a find, it focus should automatically either go to the first occurrence or to the first occurrence in the open document if an "all open documents" search is performed.  Even if focus where just put back to the previous position, a ctl-k would take one to the next occurrence of the find result.

**Comment by adamjimenez** [comment]
Ctrl-f will toggle the find panel closed and you can press F3 to jump to the next search item.
