### ISSUE TITLE
Right-click -> 'edit' on a site brings up the edit dialogue for that site for 1 second before the inputs are filled in with fields for a different site. And then I get log-in error. 

### ISSUE THREAD

**Issue by montrealks** [adamjimenez/shiftedit#352]
I made a 20 seconds video that shows what is going on

https://youtu.be/hQMxnFT31xY

**Comment by adamjimenez** [comment]
Thanks, I haven't been able to recreate this.
Which browser is it and does it occur without browser plugins enabled?

**Comment by montrealks** [comment]
this was being caused by my password manager, not by shift edit. Closing the ticket.
