### ISSUE TITLE
Inputting new content overwrites existing content

### ISSUE THREAD

**Issue by CougarB** [adamjimenez/shiftedit#354]
I am experiencing a fatal problem in trying to use ShiftEdit. I open a JavaScript file, and it's one that had one error in it, and it's marked as the single error that shows up "[1/1] Too many errors. (74% scanned). on line 174." So I was trying to comment on what I was seeing, and I was suggesting some hypotheses to myself. Since my stroke, I can't type, but I dictate into a box and then inserted into whatever I'm writing. This works in ShiftEdit just like it's always worked in ShiftEdit.

However, today — after inserting this text into ShiftEdit — I was trying to fix it from my keyboard directly. My keyboard automatically went into overwrite mode. In other words, if I put my cursor in front of the word "overwrite" and tried to insert the word "under" in front of it, the word "under " overwrites the first five letters in the word "overwrite".

Although this is never happened before, I hypothesized that something was going wrong with my dictation software.

So to test this hypothesis, I tried inserting a word manually with the keyboard. In other words I turned off the dictation software, and I typed it. However, this did not fix the problem.

I tried using my computer manually and with dictation in several other programs and on several other webpages — including this one. The problem only shows up in ShiftEdit. It does not show up anywhere else.

I couldn't get ShiftEdit to work at all in Chrome today, so I closed both Firefox Windows (Developer and Regular) and reopened them — but the problem remains.

**Comment by adamjimenez** [comment]
Overwrite mode is triggered by pressing the insert key. It sounds like that is what is happening here.
