### ISSUE TITLE
Reload of a tab works intermittently

### ISSUE THREAD

**Issue by tbirnseth** [adamjimenez/shiftedit#356]
Rigght-click a tab and selecting reload only works occasionally.  I have not been able to determine what allows it to work and what prevents it from working.  However, if one is going to edit a file that might have changed on the site, it is critical the Reload reloads the file even if something indicates that the file has not changed (like timestamp).  It should ALWAYS reload whether it's changed or not.

**Comment by adamjimenez** [comment]
I'm not able to replicate this - when it happens are there any errors in chromes js console?
Please let me know anything else that might help me track it down.
