### ISSUE TITLE
Error opening file: chdir / 

### ISSUE THREAD

**Issue by lividcreature** [adamjimenez/shiftedit#357]
Created a new directory via my CPanel file manager and populated it with Wordpress files. I then changed my theme directory, which has all proper permissions but I am getting the "Error opening file: chdir / " when I try to access it from the file browser pane.  I can see the DIR on my file manager and permissions set to proper 755. Have tried deleting Firefox cache and everything, reloading ShiftEdit numerous times. Still getting this error. Any thoughts?

**Comment by adamjimenez** [comment]
It's hard to tell with this one.
If you email me the server details I can investigate.
adam@shiftcreate.com
