### ISSUE TITLE
IDE page is dead

### ISSUE THREAD

**Issue by Resin01** [adamjimenez/shiftedit#36]
The link in your blog post points to https://shiftedit.net/ide/
This page is currently not working.

**Comment by adamjimenez** [comment]
Thanks,

I've updated the blog post. The new build is now available by switching to
the unstable channel from https://shiftedit.net/update-details

On 20 November 2015 at 11:59, Resin01 <notifications@github.com> wrote:

> The link in your blog post points to https://shiftedit.net/ide/
> This page is currently not working.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adamjimenez/shiftedit/issues/36>.
>



-- 
Best regards,
Adam Jimenez
