### ISSUE TITLE
tabs are 2 or 4 spaces

### ISSUE THREAD

**Issue by Spock77625** [adamjimenez/shiftedit#360]
For some reason clicking on tab will be 2 spaces or 4 spaces and I can't find a reason why. My default is set to 4 spaces, but I can't tell if that is for all file types.

Also, I wonder if you create a new file as PHP, or as HTML you will get different amount of spaces.

**Comment by adamjimenez** [comment]
You probably have "detect tab type" ticked in preferences which will be changing the tab size depending on what's in the file.
