### ISSUE TITLE
Not able to access

### ISSUE THREAD

**Issue by tbirnseth** [adamjimenez/shiftedit#361]
For the last 3 days, trying to access shiftedit.net/home results in a spinner in the title bar and "waiting for shiftedit" in the status bar.

Have sent emails but no response.  Started 3 days ago.

Please advise.

**Comment by adamjimenez** [comment]
Most likely a cache issue.
In Chrome go to dev tools (F12)
Go to Applications -> Clear storage -> Clear site data.
![image](https://user-images.githubusercontent.com/573192/64446287-5804df00-d0d0-11e9-85c4-d05df319dbdb.png)

**Comment by tbirnseth** [comment]
Shouldn't be closed since clearing the browser cache did not resolve the problem!
Still get title bar spinning and no shiftedit.  Please don't close issues until they're confirmed.

![image](https://user-images.githubusercontent.com/20730490/64449495-e5c2d900-d094-11e9-977b-0f1ae267339d.png)

**Comment by tbirnseth** [comment]
Working now.
