### ISSUE TITLE
css custom properties are marked as errors by linter

### ISSUE THREAD

**Issue by francisbarton** [adamjimenez/shiftedit#362]
I think this is more likely an issue with Ace, but thought worth checking in with you here first.
Where I have: 
```
#element  {
    --margin: 1rem;
    margin: calc(var(--margin) * -1);
}
```
in my CSS, this is flagged as an error (`Expected RBRACE at line 2 col 5`). But as far as I can see this should be correct CSS ([MDN web docs](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties)).

**Comment by adamjimenez** [comment]
It is ace or more specifically csslint.

Here's the [bug](https://github.com/CSSLint/csslint/issues/682)
