### ISSUE TITLE
Directory Not Showing

### ISSUE THREAD

**Issue by stilts77** [adamjimenez/shiftedit#367]
One of my directories (which is called 0) is not showing in the file tree.

On my hosting platform - I can see it and it appears to have the same properties as other folders that neighbour it.

I've noticed that this folder was not included in a back-up I made either (it's not in the zip file).

Can you help please?

In the past - I had many folders that just 'disappeared' and I blamed the hosting company... could this be linked?

**Comment by adamjimenez** [comment]
I fixed an issue a little while back with files called 0. So this should be resolved.
