### ISSUE TITLE
Random file deletion

### ISSUE THREAD

**Issue by stilts77** [adamjimenez/shiftedit#368]
I've had an issue previously where I have found many files/directories deleted.

I thought it was an issue with my hosting package... but it's just happened again.

A project I had working stopped working and it seems a file in the project had disappeared (thereby taking all its code with it).

I am positive - in the 10 minutes I was away - no one has messed with my machine...

... could this be happening somehow via this site?

**Comment by adamjimenez** [comment]
ShiftEdit does not randomly delete files.
