### ISSUE TITLE
Emmet not working

### ISSUE THREAD

**Issue by toyinal** [adamjimenez/shiftedit#370]
Emmet is checked, but div.gate then tab key does nothing. Checked and Unchecked emmet as suggested by someone but emmet still will not work.
Can you kindly indicate how to get emmet to work on shiftedit
Thanks

**Comment by adamjimenez** [comment]
![emmet](https://user-images.githubusercontent.com/573192/90388216-62b94980-e07f-11ea-866e-ed1fb391f630.gif)

I'm doing the exact same thing and it works for me. I'm using Chrome 84

Check the console for errors or blocked network requests..
