### ISSUE TITLE
Suggestion for git handling

### ISSUE THREAD

**Issue by frafor** [adamjimenez/shiftedit#372]
Please, add button to invert selections in git handling of files. Sometimes we just need to commit one or two files and it’s very cumbersome to deselect one by one a few dozens of files.

**Comment by adamjimenez** [comment]
This is already possible by clicking the checkbox at the very top

![image](https://user-images.githubusercontent.com/573192/93471721-a22bbd80-f8eb-11ea-966d-059e16e23182.png)
