### ISSUE TITLE
File tree tabs -> can't restore once closed

### ISSUE THREAD

**Issue by andyiwest** [adamjimenez/shiftedit#45]
After shrinking the 'date modifed' tab in the file tree, i can't seem to get it back again. Have refreshed.

![screen shot 2015-12-11 at 15 33 01](https://cloud.githubusercontent.com/assets/13347568/11748121/9e09e8f6-a01e-11e5-9326-74b5ba6baecc.png)

**Comment by adamjimenez** [comment]
I've got a fix for this that will prevent you being able to over-shrink.
To get them back you can run this on console:
```
delete localStorage['jstree-root-tree-column-0']; delete localStorage['jstree-root-tree-column-1']; delete localStorage['jstree-root-tree-column-2']; delete localStorage['jstree-root-tree-column-3']; 
```

Then refresh
