### ISSUE TITLE
Access Denied popup after opening file

### ISSUE THREAD

**Issue by andyiwest** [adamjimenez/shiftedit#46]
I get a popup saying access denied, but the page opens anyway.
![screen shot 2015-12-11 at 15 37 38](https://cloud.githubusercontent.com/assets/13347568/11748156/d279e76c-a01e-11e5-9119-940f31aa264b.png)

**Comment by adamjimenez** [comment]
Does this happen every time you open a file?
Try as I might, I can't recreate this.

**Comment by andyiwest** [comment]
Yep, every time, however i've now run into something more dangerous.

I switched site to check if it happens on all sites or just this, and now my pages are in an infinite loop of opening
![screen shot 2015-12-11 at 16 59 20](https://cloud.githubusercontent.com/assets/13347568/11749928/6f42cdb2-a028-11e5-9cfa-1a045b884079.png)

**Comment by andyiwest** [comment]
Infinite loop occured when having files open in one site, and then switching site and opening a diff file

**Comment by andyiwest** [comment]
Access denied confirmed to occur on more than 1 site.

Infinite loop only seems to happen with this one particular contact-list.php page on test32

**Comment by adamjimenez** [comment]
Ok I'm seeing weird behaviour in Firefox, will find out what's going on.

**Comment by adamjimenez** [comment]
Found out what's going on. It's to do with [Firefox not decoding the location.hash](https://bugzilla.mozilla.org/show_bug.cgi?id=1184589#c5).

This leads to FF never knowing that the file is already opening.
