### ISSUE TITLE
Code hinting css issue

### ISSUE THREAD

**Issue by andyiwest** [adamjimenez/shiftedit#47]
take a look a the screenshot, the code hinting box that normally appears by the side of the text is way up at the top of the editor window.

![screen shot 2015-12-21 at 09 35 21](https://cloud.githubusercontent.com/assets/13347568/11927688/39976650-a7c6-11e5-9998-2e8f84f8e6db.png)

**Comment by andyiwest** [comment]
I'm on line 360

**Comment by adamjimenez** [comment]
Thanks, I've seen this happen in Chrome but it doesn't happen every time.
