### ISSUE TITLE
Tabs become unusable on laptops with more than about 15 files open.

### ISSUE THREAD

**Issue by nsbawden** [adamjimenez/shiftedit#63]
I commonly have 40 to 50 files open. Having more than about 15 open in version 17 leaves tabs with just x's, no names. This makes the tab bar virtually useless. The old way in 16 and before allowed sliding the tabs with the mouse scroll wheel and this made having 40 or 50 files open very practical, fast and easy.

**Comment by adamjimenez** [comment]
It might be easier to jump around tabs using either alt left/right or the quick open menu - ctrl-o.
I'm not sure what else to suggest as the new tab system is in many ways less clunky than before. I'm hoping quick open is the best solution.

You can get the old version from the legacy channel:
https://shiftedit.net/update-details

Eventually the legacy version will no longer be supported so if you have any other suggestions please let me know.

**Comment by nsbawden** [comment]
Well at the moment tabs seem broken to me. The fact that you cannot have but a moderate amount of files loaded before the tabs show nothing at all about the file that is in that tab makes tabs pretty much unusable for anything but small projects.

A very quick fix would be to use live tooltips on the tabs. Then you could mouse over the tabs to instantly see what is in them without having to wait several seconds for the system tooltip to appear. At least that would make tabs more usable until something else can be implemented.

Surely there is an elegant fix? I am a developer myself and I can think of several. Unfortunately I have my own projects that I am contracted on and I don't have time to work on shiftedit or I would fix it myself. Rather I need shiftedit to work well so I can work on my other projects. Please don't take away legacy support until tabs can work with many files loaded again. Except for this feature regression, shiftedit is the best cloud IDE out there. :)

**Comment by adamjimenez** [comment]
Do you have a similar problem with too many Chrome tabs?
I'm implementing the fix with faster tooltips. Pls let me know if you have any other suggestions.

**Comment by nsbawden** [comment]
Not really in chrome. The favicon is always visible for lots of tabs, but then if there are too many I can just open another browser window. That doesn't work for shiftedit for lots of reasons, one being that I often need a lot of files loaded so that I can search and replace in all at the same time. That would not work across windows. Thanks for the tooltip addition. I will check it out in the dev channel. :)
