### ISSUE TITLE
New site from GitHub repo

### ISSUE THREAD

**Issue by justmiles** [adamjimenez/shiftedit#70]
I saw the "git url" option under "hosted sites" but it failed to import a public repo. With DevOps and microservices today, pushing to master is pushing to production. If an online IDE like ShiftEdit could support pulling, editing, and committing projects from withing the browser - that's huge. 

Am I missing something in the configs/preferences that are preventing me from checking out a git repo?

**Comment by adamjimenez** [comment]
Can you let me know the public git url?

This feature is currently in beta and limited to premier users. If you need a free trial, let me (adam@shiftcreate.com) know your email address and I will set it up.

**Comment by justmiles** [comment]
Here's the public repo: https://github.com/Copyleft-io/basestation.git

I tried both HTTP and SSH, but if it's a paid feature then that makes sense it didn't function. I'll shoot you an email about that trial.
