### ISSUE TITLE
Languages supported ?

### ISSUE THREAD

**Issue by joeblew99** [adamjimenez/shiftedit#79]
Wondering what la guages it support ?

Also a roadmap of where your thinking of taking this would be cool. 

Also think a file system abstraction might be good idea, so that it can run where the file system that you want to edit is somewhere else.

**Comment by adamjimenez** [comment]
We can support any language that ace supports. For the actively supported languages see:
https://github.com/adamjimenez/shiftedit/blob/master/shiftedit/modes.js

I don't have anything as rigid as a long term roadmap. I have a bunch of ideas and am regularly assessing feedback. I prefer to hold back surprises and avoid potential disappointments.

I'm not sure about the last point we already connect to different filesystems over ftp, dropbox etc..
