### ISSUE TITLE
tabs-definitions not showing a scroll bar.

### ISSUE THREAD

**Issue by DieHardDigitalDeveloper** [adamjimenez/shiftedit#91]
I started my account with Firefox but noticed the tabs-definitions content didn't have a scroll bar, I figured I would try Google Chrome and see if it acted any better.

Multiple attempts to log in failed.  Tried resetting my password but that failed too.  I can still log in with Firefox.

**Comment by DieHardDigitalDeveloper** [comment]
UPDATE:  I was able to log in with Chrome.  It was a plugin gumming up the works.  Still having the issue of the tabs-definitions pane not showing a scroll bar.

**Comment by adamjimenez** [comment]
Thanks Mark,
That issue will be fixed in the next update.

On 21 January 2016 at 12:02, Mark Cicchetti <notifications@github.com>
wrote:

> UPDATE: I was able to log in with Chrome. It was a plugin gumming up the
> works. Still having the issue of the tabs-definitions pane not showing a
> scroll bar.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adamjimenez/shiftedit/issues/91#issuecomment-173550376>
> .
>



-- 
Best regards,
Adam Jimenez
