### ISSUE TITLE
Duplicating a folder doesn't work

### ISSUE THREAD

**Issue by eddieharrison** [adamjimenez/shiftedit#94]
Says "loading" in notification panel and then runs through files saying "Putting 'original_folder/whatever.php'" rather than "Putting 'original_folder - Copy/whatever.php'

Version: 17.0.42

**Comment by adamjimenez** [comment]
pls try in >=17.0.52

**Comment by eddieharrison** [comment]
Still doesn't work in 17.0.53 - just says "loading cancel" in a notification for about 3 seconds, the notification then goes away and nothing's happened

**Comment by eddieharrison** [comment]
Tried this on 17.0.56 and although it seems to work better than before, it doesn't put the child files into the newly created (1) folder, they land in /public_html

**Comment by adamjimenez** [comment]
Thanks, I've had another stab at this. Will be in 17.0.59
